#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 116
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 47
#define ALIAS_COUNT 0
#define TOKEN_COUNT 26
#define EXTERNAL_TOKEN_COUNT 6
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  anon_sym_LBRACE = 2,
  aux_sym_attributes_token1 = 3,
  anon_sym_RBRACE = 4,
  anon_sym_POUND = 5,
  aux_sym_attribute_id_token1 = 6,
  anon_sym_DOT = 7,
  anon_sym_EQ = 8,
  sym_attribute_key = 9,
  sym_attribute_value_quoted = 10,
  sym_attribute_value_unquoted = 11,
  sym_heading_marker = 12,
  sym_code_block_marker = 13,
  aux_sym_code_token1 = 14,
  sym_language = 15,
  sym_verbatim = 16,
  anon_sym__ = 17,
  anon_sym_STAR = 18,
  sym__text = 19,
  sym__close_paragraph = 20,
  sym__block_close = 21,
  sym__div_marker_begin = 22,
  sym__div_marker_end = 23,
  sym__block_quote_begin = 24,
  sym__ignored = 25,
  sym_document = 26,
  sym__block = 27,
  sym_attributes = 28,
  sym_attribute_id = 29,
  sym_attribute_class = 30,
  sym_attribute_key_value = 31,
  sym_heading = 32,
  sym_block_quote = 33,
  sym_div = 34,
  sym_code_block = 35,
  sym_code = 36,
  sym_paragraph = 37,
  aux_sym__inline = 38,
  sym_emphasis = 39,
  sym_strong_emphasis = 40,
  sym__fallback = 41,
  sym__fallback_star = 42,
  aux_sym_document_repeat1 = 43,
  aux_sym_attributes_repeat1 = 44,
  aux_sym_heading_repeat1 = 45,
  aux_sym_code_repeat1 = 46,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [anon_sym_LBRACE] = "{",
  [aux_sym_attributes_token1] = "attributes_token1",
  [anon_sym_RBRACE] = "}",
  [anon_sym_POUND] = "#",
  [aux_sym_attribute_id_token1] = "attribute_id_token1",
  [anon_sym_DOT] = ".",
  [anon_sym_EQ] = "=",
  [sym_attribute_key] = "attribute_key",
  [sym_attribute_value_quoted] = "attribute_value_quoted",
  [sym_attribute_value_unquoted] = "attribute_value_unquoted",
  [sym_heading_marker] = "heading_marker",
  [sym_code_block_marker] = "code_block_marker",
  [aux_sym_code_token1] = "code_token1",
  [sym_language] = "language",
  [sym_verbatim] = "verbatim",
  [anon_sym__] = "_",
  [anon_sym_STAR] = "*",
  [sym__text] = "_text",
  [sym__close_paragraph] = "_close_paragraph",
  [sym__block_close] = "_block_close",
  [sym__div_marker_begin] = "div_marker",
  [sym__div_marker_end] = "div_marker",
  [sym__block_quote_begin] = "_block_quote_begin",
  [sym__ignored] = "_ignored",
  [sym_document] = "document",
  [sym__block] = "_block",
  [sym_attributes] = "attributes",
  [sym_attribute_id] = "attribute_id",
  [sym_attribute_class] = "attribute_class",
  [sym_attribute_key_value] = "attribute_key_value",
  [sym_heading] = "heading",
  [sym_block_quote] = "block_quote",
  [sym_div] = "div",
  [sym_code_block] = "code_block",
  [sym_code] = "code",
  [sym_paragraph] = "paragraph",
  [aux_sym__inline] = "_inline",
  [sym_emphasis] = "emphasis",
  [sym_strong_emphasis] = "strong_emphasis",
  [sym__fallback] = "_fallback",
  [sym__fallback_star] = "_fallback_star",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_attributes_repeat1] = "attributes_repeat1",
  [aux_sym_heading_repeat1] = "heading_repeat1",
  [aux_sym_code_repeat1] = "code_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [aux_sym_attributes_token1] = aux_sym_attributes_token1,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_attribute_id_token1] = aux_sym_attribute_id_token1,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_attribute_key] = sym_attribute_key,
  [sym_attribute_value_quoted] = sym_attribute_value_quoted,
  [sym_attribute_value_unquoted] = sym_attribute_value_unquoted,
  [sym_heading_marker] = sym_heading_marker,
  [sym_code_block_marker] = sym_code_block_marker,
  [aux_sym_code_token1] = aux_sym_code_token1,
  [sym_language] = sym_language,
  [sym_verbatim] = sym_verbatim,
  [anon_sym__] = anon_sym__,
  [anon_sym_STAR] = anon_sym_STAR,
  [sym__text] = sym__text,
  [sym__close_paragraph] = sym__close_paragraph,
  [sym__block_close] = sym__block_close,
  [sym__div_marker_begin] = sym__div_marker_begin,
  [sym__div_marker_end] = sym__div_marker_begin,
  [sym__block_quote_begin] = sym__block_quote_begin,
  [sym__ignored] = sym__ignored,
  [sym_document] = sym_document,
  [sym__block] = sym__block,
  [sym_attributes] = sym_attributes,
  [sym_attribute_id] = sym_attribute_id,
  [sym_attribute_class] = sym_attribute_class,
  [sym_attribute_key_value] = sym_attribute_key_value,
  [sym_heading] = sym_heading,
  [sym_block_quote] = sym_block_quote,
  [sym_div] = sym_div,
  [sym_code_block] = sym_code_block,
  [sym_code] = sym_code,
  [sym_paragraph] = sym_paragraph,
  [aux_sym__inline] = aux_sym__inline,
  [sym_emphasis] = sym_emphasis,
  [sym_strong_emphasis] = sym_strong_emphasis,
  [sym__fallback] = sym__fallback,
  [sym__fallback_star] = sym__fallback_star,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_attributes_repeat1] = aux_sym_attributes_repeat1,
  [aux_sym_heading_repeat1] = aux_sym_heading_repeat1,
  [aux_sym_code_repeat1] = aux_sym_code_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_attributes_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_attribute_id_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_key] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value_quoted] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value_unquoted] = {
    .visible = true,
    .named = true,
  },
  [sym_heading_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_code_block_marker] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_code_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_language] = {
    .visible = true,
    .named = true,
  },
  [sym_verbatim] = {
    .visible = true,
    .named = true,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [sym__text] = {
    .visible = false,
    .named = true,
  },
  [sym__close_paragraph] = {
    .visible = false,
    .named = true,
  },
  [sym__block_close] = {
    .visible = false,
    .named = true,
  },
  [sym__div_marker_begin] = {
    .visible = true,
    .named = true,
  },
  [sym__div_marker_end] = {
    .visible = true,
    .named = true,
  },
  [sym__block_quote_begin] = {
    .visible = false,
    .named = true,
  },
  [sym__ignored] = {
    .visible = false,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__block] = {
    .visible = false,
    .named = true,
  },
  [sym_attributes] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_id] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_class] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_key_value] = {
    .visible = true,
    .named = true,
  },
  [sym_heading] = {
    .visible = true,
    .named = true,
  },
  [sym_block_quote] = {
    .visible = true,
    .named = true,
  },
  [sym_div] = {
    .visible = true,
    .named = true,
  },
  [sym_code_block] = {
    .visible = true,
    .named = true,
  },
  [sym_code] = {
    .visible = true,
    .named = true,
  },
  [sym_paragraph] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__inline] = {
    .visible = false,
    .named = false,
  },
  [sym_emphasis] = {
    .visible = true,
    .named = true,
  },
  [sym_strong_emphasis] = {
    .visible = true,
    .named = true,
  },
  [sym__fallback] = {
    .visible = false,
    .named = true,
  },
  [sym__fallback_star] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_attributes_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_heading_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_code_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 2,
  [7] = 5,
  [8] = 8,
  [9] = 4,
  [10] = 10,
  [11] = 3,
  [12] = 8,
  [13] = 13,
  [14] = 13,
  [15] = 15,
  [16] = 15,
  [17] = 17,
  [18] = 17,
  [19] = 19,
  [20] = 20,
  [21] = 19,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 25,
  [27] = 27,
  [28] = 27,
  [29] = 24,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 34,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 31,
  [45] = 45,
  [46] = 46,
  [47] = 30,
  [48] = 48,
  [49] = 48,
  [50] = 43,
  [51] = 42,
  [52] = 41,
  [53] = 33,
  [54] = 45,
  [55] = 39,
  [56] = 46,
  [57] = 40,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 58,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 65,
  [67] = 64,
  [68] = 62,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 80,
  [82] = 79,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 83,
  [87] = 84,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 89,
  [92] = 88,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 76,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 75,
  [104] = 104,
  [105] = 105,
  [106] = 100,
  [107] = 107,
  [108] = 104,
  [109] = 109,
  [110] = 77,
  [111] = 102,
  [112] = 107,
  [113] = 113,
  [114] = 109,
  [115] = 113,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(29);
      if (lookahead == '\n') ADVANCE(30);
      if (lookahead == '\r') SKIP(0);
      if (lookahead == '"') ADVANCE(8);
      if (lookahead == '#') ADVANCE(35);
      if (lookahead == '\'') ADVANCE(10);
      if (lookahead == '*') ADVANCE(53);
      if (lookahead == '.') ADVANCE(37);
      if (lookahead == '=') ADVANCE(38);
      if (lookahead == '_') ADVANCE(52);
      if (lookahead == '`') ADVANCE(19);
      if (lookahead == '{') ADVANCE(31);
      if (lookahead == '}') ADVANCE(34);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(30);
      if (lookahead == '\r') ADVANCE(56);
      if (lookahead == '*') ADVANCE(53);
      if (lookahead == '_') ADVANCE(52);
      if (lookahead == '`') ADVANCE(60);
      if (lookahead != 0) ADVANCE(54);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(30);
      if (lookahead == '\r') ADVANCE(57);
      if (lookahead == '*') ADVANCE(53);
      if (lookahead == '_') ADVANCE(52);
      if (lookahead == '`') ADVANCE(60);
      if (lookahead == '{') ADVANCE(31);
      if (lookahead != 0) ADVANCE(54);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(30);
      if (lookahead == '\r') SKIP(3);
      if (lookahead == '{') ADVANCE(31);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(50);
      END_STATE();
    case 4:
      if (lookahead == '\r') ADVANCE(32);
      if (lookahead == '#') ADVANCE(35);
      if (lookahead == '.') ADVANCE(37);
      if (lookahead == '}') ADVANCE(34);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead == ':' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 5:
      if (lookahead == '\r') SKIP(5);
      if (lookahead == '#') ADVANCE(35);
      if (lookahead == '.') ADVANCE(37);
      if (lookahead == '`') ADVANCE(21);
      if (lookahead == '}') ADVANCE(34);
      if (lookahead == ':' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 6:
      if (lookahead == '\r') SKIP(6);
      if (lookahead == '"') ADVANCE(8);
      if (lookahead == '\'') ADVANCE(10);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '}') ADVANCE(41);
      END_STATE();
    case 7:
      if (lookahead == '\r') SKIP(7);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '}') ADVANCE(36);
      END_STATE();
    case 8:
      if (lookahead == '"') ADVANCE(40);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == '#') ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(42);
      END_STATE();
    case 10:
      if (lookahead == '\'') ADVANCE(40);
      if (lookahead != 0) ADVANCE(10);
      END_STATE();
    case 11:
      if (lookahead == '`') ADVANCE(44);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(17);
      END_STATE();
    case 12:
      if (lookahead == '`') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(12);
      END_STATE();
    case 13:
      if (lookahead == '`') ADVANCE(51);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 14:
      if (lookahead == '`') ADVANCE(51);
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 15:
      if (lookahead == '`') ADVANCE(51);
      if (lookahead != 0) ADVANCE(22);
      END_STATE();
    case 16:
      if (lookahead == '`') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(20);
      END_STATE();
    case 17:
      if (lookahead == '`') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(17);
      END_STATE();
    case 18:
      if (lookahead == '`') ADVANCE(43);
      END_STATE();
    case 19:
      if (lookahead == '`') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(12);
      END_STATE();
    case 20:
      if (lookahead == '`') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(20);
      END_STATE();
    case 21:
      if (lookahead == '`') ADVANCE(18);
      END_STATE();
    case 22:
      if (lookahead == '`') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(22);
      END_STATE();
    case 23:
      if (lookahead == '`') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(17);
      END_STATE();
    case 24:
      if (lookahead == '`') ADVANCE(14);
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 25:
      if (lookahead == '`') ADVANCE(26);
      if (lookahead != 0) ADVANCE(22);
      END_STATE();
    case 26:
      if (lookahead == '`') ADVANCE(15);
      if (lookahead != 0) ADVANCE(22);
      END_STATE();
    case 27:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '`') ADVANCE(22);
      END_STATE();
    case 28:
      if (eof) ADVANCE(29);
      if (lookahead == '\n') ADVANCE(30);
      if (lookahead == '\r') ADVANCE(55);
      if (lookahead == '#') ADVANCE(58);
      if (lookahead == '*') ADVANCE(53);
      if (lookahead == '_') ADVANCE(52);
      if (lookahead == '`') ADVANCE(59);
      if (lookahead != 0) ADVANCE(54);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_attributes_token1);
      if (lookahead == '\r') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(33);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_attributes_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_attribute_id_token1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '}') ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_attribute_key);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_attribute_value_quoted);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_attribute_value_unquoted);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '}') ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_heading_marker);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_code_block_marker);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_code_block_marker);
      if (lookahead == '`') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(20);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_code_block_marker);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(49);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_code_token1);
      if (lookahead == '\r') ADVANCE(46);
      if (lookahead == '`') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(49);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_code_token1);
      if (lookahead == '`') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(49);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_code_token1);
      if (lookahead == '`') ADVANCE(47);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(49);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_code_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_language);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{') ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_verbatim);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym__);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym__text);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == '\r') ADVANCE(55);
      if (lookahead == '#') ADVANCE(58);
      if (lookahead == '*') ADVANCE(53);
      if (lookahead == '_') ADVANCE(52);
      if (lookahead == '`') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(54);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == '\r') ADVANCE(56);
      if (lookahead == '*') ADVANCE(53);
      if (lookahead == '_') ADVANCE(52);
      if (lookahead == '`') ADVANCE(60);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(54);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == '\r') ADVANCE(57);
      if (lookahead == '*') ADVANCE(53);
      if (lookahead == '_') ADVANCE(52);
      if (lookahead == '`') ADVANCE(60);
      if (lookahead == '{') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(54);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == '#') ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(42);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == '`') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(12);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == '`') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(12);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 28, .external_lex_state = 2},
  [2] = {.lex_state = 28, .external_lex_state = 3},
  [3] = {.lex_state = 28, .external_lex_state = 3},
  [4] = {.lex_state = 28, .external_lex_state = 3},
  [5] = {.lex_state = 28, .external_lex_state = 3},
  [6] = {.lex_state = 28, .external_lex_state = 3},
  [7] = {.lex_state = 28, .external_lex_state = 3},
  [8] = {.lex_state = 28, .external_lex_state = 3},
  [9] = {.lex_state = 28, .external_lex_state = 3},
  [10] = {.lex_state = 28, .external_lex_state = 2},
  [11] = {.lex_state = 28, .external_lex_state = 3},
  [12] = {.lex_state = 28, .external_lex_state = 3},
  [13] = {.lex_state = 28, .external_lex_state = 3},
  [14] = {.lex_state = 28, .external_lex_state = 3},
  [15] = {.lex_state = 28, .external_lex_state = 2},
  [16] = {.lex_state = 28, .external_lex_state = 3},
  [17] = {.lex_state = 1, .external_lex_state = 4},
  [18] = {.lex_state = 1, .external_lex_state = 4},
  [19] = {.lex_state = 1, .external_lex_state = 4},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 1, .external_lex_state = 4},
  [22] = {.lex_state = 1, .external_lex_state = 4},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 28, .external_lex_state = 5},
  [25] = {.lex_state = 28, .external_lex_state = 6},
  [26] = {.lex_state = 28, .external_lex_state = 5},
  [27] = {.lex_state = 28, .external_lex_state = 6},
  [28] = {.lex_state = 28, .external_lex_state = 5},
  [29] = {.lex_state = 28, .external_lex_state = 6},
  [30] = {.lex_state = 28, .external_lex_state = 2},
  [31] = {.lex_state = 28, .external_lex_state = 2},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 28, .external_lex_state = 2},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 28, .external_lex_state = 3},
  [40] = {.lex_state = 28, .external_lex_state = 3},
  [41] = {.lex_state = 28, .external_lex_state = 2},
  [42] = {.lex_state = 28, .external_lex_state = 2},
  [43] = {.lex_state = 28, .external_lex_state = 2},
  [44] = {.lex_state = 28, .external_lex_state = 3},
  [45] = {.lex_state = 28, .external_lex_state = 2},
  [46] = {.lex_state = 28, .external_lex_state = 3},
  [47] = {.lex_state = 28, .external_lex_state = 3},
  [48] = {.lex_state = 28, .external_lex_state = 3},
  [49] = {.lex_state = 28, .external_lex_state = 2},
  [50] = {.lex_state = 28, .external_lex_state = 3},
  [51] = {.lex_state = 28, .external_lex_state = 3},
  [52] = {.lex_state = 28, .external_lex_state = 3},
  [53] = {.lex_state = 28, .external_lex_state = 3},
  [54] = {.lex_state = 28, .external_lex_state = 3},
  [55] = {.lex_state = 28, .external_lex_state = 2},
  [56] = {.lex_state = 28, .external_lex_state = 2},
  [57] = {.lex_state = 28, .external_lex_state = 2},
  [58] = {.lex_state = 4},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 1},
  [61] = {.lex_state = 4},
  [62] = {.lex_state = 5},
  [63] = {.lex_state = 5},
  [64] = {.lex_state = 5},
  [65] = {.lex_state = 5},
  [66] = {.lex_state = 5},
  [67] = {.lex_state = 5},
  [68] = {.lex_state = 5},
  [69] = {.lex_state = 1, .external_lex_state = 4},
  [70] = {.lex_state = 4},
  [71] = {.lex_state = 1},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 4},
  [74] = {.lex_state = 4},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 1},
  [77] = {.lex_state = 1},
  [78] = {.lex_state = 4},
  [79] = {.lex_state = 3},
  [80] = {.lex_state = 46},
  [81] = {.lex_state = 46},
  [82] = {.lex_state = 3},
  [83] = {.lex_state = 46},
  [84] = {.lex_state = 46},
  [85] = {.lex_state = 5},
  [86] = {.lex_state = 46},
  [87] = {.lex_state = 46},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 46},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 46},
  [94] = {.lex_state = 6},
  [95] = {.lex_state = 46},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 7},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 5},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 5},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 5},
  [105] = {.lex_state = 7},
  [106] = {.lex_state = 5},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 5},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 5},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_attribute_value_quoted] = ACTIONS(1),
    [sym_code_block_marker] = ACTIONS(1),
    [sym_verbatim] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [sym__close_paragraph] = ACTIONS(1),
    [sym__block_close] = ACTIONS(1),
    [sym__div_marker_begin] = ACTIONS(1),
    [sym__div_marker_end] = ACTIONS(1),
    [sym__block_quote_begin] = ACTIONS(1),
    [sym__ignored] = ACTIONS(1),
  },
  [1] = {
    [sym_document] = STATE(101),
    [sym__block] = STATE(10),
    [sym_heading] = STATE(10),
    [sym_block_quote] = STATE(10),
    [sym_div] = STATE(10),
    [sym_code_block] = STATE(10),
    [sym_paragraph] = STATE(10),
    [aux_sym__inline] = STATE(38),
    [sym_emphasis] = STATE(38),
    [sym_strong_emphasis] = STATE(38),
    [sym__fallback] = STATE(38),
    [sym__fallback_star] = STATE(38),
    [aux_sym_document_repeat1] = STATE(10),
    [aux_sym_heading_repeat1] = STATE(19),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(5),
    [sym_heading_marker] = ACTIONS(7),
    [sym_code_block_marker] = ACTIONS(9),
    [sym_verbatim] = ACTIONS(11),
    [anon_sym__] = ACTIONS(13),
    [anon_sym_STAR] = ACTIONS(15),
    [sym__text] = ACTIONS(11),
    [sym__div_marker_begin] = ACTIONS(17),
    [sym__block_quote_begin] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(13), 1,
      anon_sym__,
    ACTIONS(15), 1,
      anon_sym_STAR,
    ACTIONS(21), 1,
      anon_sym_LF,
    ACTIONS(23), 1,
      sym_heading_marker,
    ACTIONS(25), 1,
      sym_code_block_marker,
    ACTIONS(27), 1,
      sym__block_close,
    ACTIONS(29), 1,
      sym__div_marker_begin,
    ACTIONS(31), 1,
      sym__block_quote_begin,
    STATE(21), 1,
      aux_sym_heading_repeat1,
    ACTIONS(11), 2,
      sym_verbatim,
      sym__text,
    STATE(38), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
    STATE(16), 7,
      sym__block,
      sym_heading,
      sym_block_quote,
      sym_div,
      sym_code_block,
      sym_paragraph,
      aux_sym_document_repeat1,
  [48] = 12,
    ACTIONS(13), 1,
      anon_sym__,
    ACTIONS(15), 1,
      anon_sym_STAR,
    ACTIONS(21), 1,
      anon_sym_LF,
    ACTIONS(23), 1,
      sym_heading_marker,
    ACTIONS(25), 1,
      sym_code_block_marker,
    ACTIONS(29), 1,
      sym__div_marker_begin,
    ACTIONS(31), 1,
      sym__block_quote_begin,
    ACTIONS(33), 1,
      sym__block_close,
    STATE(21), 1,
      aux_sym_heading_repeat1,
    ACTIONS(11), 2,
      sym_verbatim,
      sym__text,
    STATE(38), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
    STATE(16), 7,
      sym__block,
      sym_heading,
      sym_block_quote,
      sym_div,
      sym_code_block,
      sym_paragraph,
      aux_sym_document_repeat1,
  [96] = 12,
    ACTIONS(13), 1,
      anon_sym__,
    ACTIONS(15), 1,
      anon_sym_STAR,
    ACTIONS(23), 1,
      sym_heading_marker,
    ACTIONS(25), 1,
      sym_code_block_marker,
    ACTIONS(29), 1,
      sym__div_marker_begin,
    ACTIONS(31), 1,
      sym__block_quote_begin,
    ACTIONS(35), 1,
      anon_sym_LF,
    ACTIONS(37), 1,
      sym__block_close,
    STATE(21), 1,
      aux_sym_heading_repeat1,
    ACTIONS(11), 2,
      sym_verbatim,
      sym__text,
    STATE(38), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
    STATE(3), 7,
      sym__block,
      sym_heading,
      sym_block_quote,
      sym_div,
      sym_code_block,
      sym_paragraph,
      aux_sym_document_repeat1,
  [144] = 12,
    ACTIONS(13), 1,
      anon_sym__,
    ACTIONS(15), 1,
      anon_sym_STAR,
    ACTIONS(21), 1,
      anon_sym_LF,
    ACTIONS(23), 1,
      sym_heading_marker,
    ACTIONS(25), 1,
      sym_code_block_marker,
    ACTIONS(29), 1,
      sym__div_marker_begin,
    ACTIONS(31), 1,
      sym__block_quote_begin,
    ACTIONS(37), 1,
      sym__block_close,
    STATE(21), 1,
      aux_sym_heading_repeat1,
    ACTIONS(11), 2,
      sym_verbatim,
      sym__text,
    STATE(38), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
    STATE(16), 7,
      sym__block,
      sym_heading,
      sym_block_quote,
      sym_div,
      sym_code_block,
      sym_paragraph,
      aux_sym_document_repeat1,
  [192] = 12,
    ACTIONS(13), 1,
      anon_sym__,
    ACTIONS(15), 1,
      anon_sym_STAR,
    ACTIONS(21), 1,
      anon_sym_LF,
    ACTIONS(23), 1,
      sym_heading_marker,
    ACTIONS(25), 1,
      sym_code_block_marker,
    ACTIONS(29), 1,
      sym__div_marker_begin,
    ACTIONS(31), 1,
      sym__block_quote_begin,
    ACTIONS(39), 1,
      sym__block_close,
    STATE(21), 1,
      aux_sym_heading_repeat1,
    ACTIONS(11), 2,
      sym_verbatim,
      sym__text,
    STATE(38), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
    STATE(16), 7,
      sym__block,
      sym_heading,
      sym_block_quote,
      sym_div,
      sym_code_block,
      sym_paragraph,
      aux_sym_document_repeat1,
  [240] = 12,
    ACTIONS(13), 1,
      anon_sym__,
    ACTIONS(15), 1,
      anon_sym_STAR,
    ACTIONS(21), 1,
      anon_sym_LF,
    ACTIONS(23), 1,
      sym_heading_marker,
    ACTIONS(25), 1,
      sym_code_block_marker,
    ACTIONS(29), 1,
      sym__div_marker_begin,
    ACTIONS(31), 1,
      sym__block_quote_begin,
    ACTIONS(41), 1,
      sym__block_close,
    STATE(21), 1,
      aux_sym_heading_repeat1,
    ACTIONS(11), 2,
      sym_verbatim,
      sym__text,
    STATE(38), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
    STATE(16), 7,
      sym__block,
      sym_heading,
      sym_block_quote,
      sym_div,
      sym_code_block,
      sym_paragraph,
      aux_sym_document_repeat1,
  [288] = 12,
    ACTIONS(13), 1,
      anon_sym__,
    ACTIONS(15), 1,
      anon_sym_STAR,
    ACTIONS(23), 1,
      sym_heading_marker,
    ACTIONS(25), 1,
      sym_code_block_marker,
    ACTIONS(29), 1,
      sym__div_marker_begin,
    ACTIONS(31), 1,
      sym__block_quote_begin,
    ACTIONS(43), 1,
      anon_sym_LF,
    ACTIONS(45), 1,
      sym__block_close,
    STATE(21), 1,
      aux_sym_heading_repeat1,
    ACTIONS(11), 2,
      sym_verbatim,
      sym__text,
    STATE(38), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
    STATE(5), 7,
      sym__block,
      sym_heading,
      sym_block_quote,
      sym_div,
      sym_code_block,
      sym_paragraph,
      aux_sym_document_repeat1,
  [336] = 12,
    ACTIONS(13), 1,
      anon_sym__,
    ACTIONS(15), 1,
      anon_sym_STAR,
    ACTIONS(23), 1,
      sym_heading_marker,
    ACTIONS(25), 1,
      sym_code_block_marker,
    ACTIONS(29), 1,
      sym__div_marker_begin,
    ACTIONS(31), 1,
      sym__block_quote_begin,
    ACTIONS(41), 1,
      sym__block_close,
    ACTIONS(47), 1,
      anon_sym_LF,
    STATE(21), 1,
      aux_sym_heading_repeat1,
    ACTIONS(11), 2,
      sym_verbatim,
      sym__text,
    STATE(38), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
    STATE(11), 7,
      sym__block,
      sym_heading,
      sym_block_quote,
      sym_div,
      sym_code_block,
      sym_paragraph,
      aux_sym_document_repeat1,
  [384] = 12,
    ACTIONS(7), 1,
      sym_heading_marker,
    ACTIONS(9), 1,
      sym_code_block_marker,
    ACTIONS(13), 1,
      anon_sym__,
    ACTIONS(15), 1,
      anon_sym_STAR,
    ACTIONS(17), 1,
      sym__div_marker_begin,
    ACTIONS(19), 1,
      sym__block_quote_begin,
    ACTIONS(49), 1,
      ts_builtin_sym_end,
    ACTIONS(51), 1,
      anon_sym_LF,
    STATE(19), 1,
      aux_sym_heading_repeat1,
    ACTIONS(11), 2,
      sym_verbatim,
      sym__text,
    STATE(38), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
    STATE(15), 7,
      sym__block,
      sym_heading,
      sym_block_quote,
      sym_div,
      sym_code_block,
      sym_paragraph,
      aux_sym_document_repeat1,
  [432] = 12,
    ACTIONS(13), 1,
      anon_sym__,
    ACTIONS(15), 1,
      anon_sym_STAR,
    ACTIONS(21), 1,
      anon_sym_LF,
    ACTIONS(23), 1,
      sym_heading_marker,
    ACTIONS(25), 1,
      sym_code_block_marker,
    ACTIONS(29), 1,
      sym__div_marker_begin,
    ACTIONS(31), 1,
      sym__block_quote_begin,
    ACTIONS(53), 1,
      sym__block_close,
    STATE(21), 1,
      aux_sym_heading_repeat1,
    ACTIONS(11), 2,
      sym_verbatim,
      sym__text,
    STATE(38), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
    STATE(16), 7,
      sym__block,
      sym_heading,
      sym_block_quote,
      sym_div,
      sym_code_block,
      sym_paragraph,
      aux_sym_document_repeat1,
  [480] = 12,
    ACTIONS(13), 1,
      anon_sym__,
    ACTIONS(15), 1,
      anon_sym_STAR,
    ACTIONS(23), 1,
      sym_heading_marker,
    ACTIONS(25), 1,
      sym_code_block_marker,
    ACTIONS(29), 1,
      sym__div_marker_begin,
    ACTIONS(31), 1,
      sym__block_quote_begin,
    ACTIONS(55), 1,
      anon_sym_LF,
    ACTIONS(57), 1,
      sym__block_close,
    STATE(21), 1,
      aux_sym_heading_repeat1,
    ACTIONS(11), 2,
      sym_verbatim,
      sym__text,
    STATE(38), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
    STATE(7), 7,
      sym__block,
      sym_heading,
      sym_block_quote,
      sym_div,
      sym_code_block,
      sym_paragraph,
      aux_sym_document_repeat1,
  [528] = 12,
    ACTIONS(13), 1,
      anon_sym__,
    ACTIONS(15), 1,
      anon_sym_STAR,
    ACTIONS(23), 1,
      sym_heading_marker,
    ACTIONS(25), 1,
      sym_code_block_marker,
    ACTIONS(29), 1,
      sym__div_marker_begin,
    ACTIONS(31), 1,
      sym__block_quote_begin,
    ACTIONS(59), 1,
      anon_sym_LF,
    ACTIONS(61), 1,
      sym__block_close,
    STATE(21), 1,
      aux_sym_heading_repeat1,
    ACTIONS(11), 2,
      sym_verbatim,
      sym__text,
    STATE(38), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
    STATE(2), 7,
      sym__block,
      sym_heading,
      sym_block_quote,
      sym_div,
      sym_code_block,
      sym_paragraph,
      aux_sym_document_repeat1,
  [576] = 12,
    ACTIONS(13), 1,
      anon_sym__,
    ACTIONS(15), 1,
      anon_sym_STAR,
    ACTIONS(23), 1,
      sym_heading_marker,
    ACTIONS(25), 1,
      sym_code_block_marker,
    ACTIONS(29), 1,
      sym__div_marker_begin,
    ACTIONS(31), 1,
      sym__block_quote_begin,
    ACTIONS(63), 1,
      anon_sym_LF,
    ACTIONS(65), 1,
      sym__block_close,
    STATE(21), 1,
      aux_sym_heading_repeat1,
    ACTIONS(11), 2,
      sym_verbatim,
      sym__text,
    STATE(38), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
    STATE(6), 7,
      sym__block,
      sym_heading,
      sym_block_quote,
      sym_div,
      sym_code_block,
      sym_paragraph,
      aux_sym_document_repeat1,
  [624] = 12,
    ACTIONS(67), 1,
      ts_builtin_sym_end,
    ACTIONS(69), 1,
      anon_sym_LF,
    ACTIONS(72), 1,
      sym_heading_marker,
    ACTIONS(75), 1,
      sym_code_block_marker,
    ACTIONS(81), 1,
      anon_sym__,
    ACTIONS(84), 1,
      anon_sym_STAR,
    ACTIONS(87), 1,
      sym__div_marker_begin,
    ACTIONS(90), 1,
      sym__block_quote_begin,
    STATE(19), 1,
      aux_sym_heading_repeat1,
    ACTIONS(78), 2,
      sym_verbatim,
      sym__text,
    STATE(38), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
    STATE(15), 7,
      sym__block,
      sym_heading,
      sym_block_quote,
      sym_div,
      sym_code_block,
      sym_paragraph,
      aux_sym_document_repeat1,
  [672] = 12,
    ACTIONS(67), 1,
      sym__block_close,
    ACTIONS(81), 1,
      anon_sym__,
    ACTIONS(84), 1,
      anon_sym_STAR,
    ACTIONS(93), 1,
      anon_sym_LF,
    ACTIONS(96), 1,
      sym_heading_marker,
    ACTIONS(99), 1,
      sym_code_block_marker,
    ACTIONS(102), 1,
      sym__div_marker_begin,
    ACTIONS(105), 1,
      sym__block_quote_begin,
    STATE(21), 1,
      aux_sym_heading_repeat1,
    ACTIONS(78), 2,
      sym_verbatim,
      sym__text,
    STATE(38), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
    STATE(16), 7,
      sym__block,
      sym_heading,
      sym_block_quote,
      sym_div,
      sym_code_block,
      sym_paragraph,
      aux_sym_document_repeat1,
  [720] = 7,
    ACTIONS(13), 1,
      anon_sym__,
    ACTIONS(15), 1,
      anon_sym_STAR,
    ACTIONS(108), 1,
      anon_sym_LF,
    ACTIONS(110), 1,
      sym__close_paragraph,
    STATE(22), 1,
      aux_sym_heading_repeat1,
    ACTIONS(11), 2,
      sym_verbatim,
      sym__text,
    STATE(38), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
  [747] = 7,
    ACTIONS(13), 1,
      anon_sym__,
    ACTIONS(15), 1,
      anon_sym_STAR,
    ACTIONS(112), 1,
      anon_sym_LF,
    ACTIONS(114), 1,
      sym__close_paragraph,
    STATE(22), 1,
      aux_sym_heading_repeat1,
    ACTIONS(11), 2,
      sym_verbatim,
      sym__text,
    STATE(38), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
  [774] = 7,
    ACTIONS(13), 1,
      anon_sym__,
    ACTIONS(15), 1,
      anon_sym_STAR,
    ACTIONS(116), 1,
      anon_sym_LF,
    ACTIONS(118), 1,
      sym__close_paragraph,
    STATE(22), 1,
      aux_sym_heading_repeat1,
    ACTIONS(11), 2,
      sym_verbatim,
      sym__text,
    STATE(38), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
  [801] = 7,
    ACTIONS(120), 1,
      anon_sym_LF,
    ACTIONS(122), 1,
      anon_sym_LBRACE,
    ACTIONS(128), 1,
      anon_sym__,
    ACTIONS(132), 1,
      anon_sym_STAR,
    STATE(71), 1,
      sym_attributes,
    ACTIONS(124), 2,
      sym_verbatim,
      sym__text,
    STATE(60), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
  [828] = 7,
    ACTIONS(13), 1,
      anon_sym__,
    ACTIONS(15), 1,
      anon_sym_STAR,
    ACTIONS(136), 1,
      anon_sym_LF,
    ACTIONS(138), 1,
      sym__close_paragraph,
    STATE(22), 1,
      aux_sym_heading_repeat1,
    ACTIONS(11), 2,
      sym_verbatim,
      sym__text,
    STATE(38), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
  [855] = 7,
    ACTIONS(140), 1,
      anon_sym_LF,
    ACTIONS(145), 1,
      anon_sym__,
    ACTIONS(148), 1,
      anon_sym_STAR,
    ACTIONS(151), 1,
      sym__close_paragraph,
    STATE(22), 1,
      aux_sym_heading_repeat1,
    ACTIONS(142), 2,
      sym_verbatim,
      sym__text,
    STATE(38), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
  [882] = 7,
    ACTIONS(122), 1,
      anon_sym_LBRACE,
    ACTIONS(153), 1,
      anon_sym_LF,
    ACTIONS(159), 1,
      anon_sym__,
    ACTIONS(163), 1,
      anon_sym_STAR,
    STATE(72), 1,
      sym_attributes,
    ACTIONS(155), 2,
      sym_verbatim,
      sym__text,
    STATE(59), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
  [909] = 3,
    ACTIONS(171), 1,
      sym__div_marker_end,
    ACTIONS(169), 3,
      sym__block_close,
      sym__div_marker_begin,
      sym__block_quote_begin,
    ACTIONS(167), 7,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      sym_verbatim,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [927] = 3,
    ACTIONS(177), 1,
      sym__div_marker_end,
    ACTIONS(173), 3,
      sym__div_marker_begin,
      sym__block_quote_begin,
      ts_builtin_sym_end,
    ACTIONS(175), 7,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      sym_verbatim,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [945] = 3,
    ACTIONS(179), 1,
      sym__div_marker_end,
    ACTIONS(173), 3,
      sym__block_close,
      sym__div_marker_begin,
      sym__block_quote_begin,
    ACTIONS(175), 7,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      sym_verbatim,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [963] = 3,
    ACTIONS(185), 1,
      sym__div_marker_end,
    ACTIONS(181), 3,
      sym__div_marker_begin,
      sym__block_quote_begin,
      ts_builtin_sym_end,
    ACTIONS(183), 7,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      sym_verbatim,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [981] = 3,
    ACTIONS(187), 1,
      sym__div_marker_end,
    ACTIONS(181), 3,
      sym__block_close,
      sym__div_marker_begin,
      sym__block_quote_begin,
    ACTIONS(183), 7,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      sym_verbatim,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [999] = 3,
    ACTIONS(189), 1,
      sym__div_marker_end,
    ACTIONS(169), 3,
      sym__div_marker_begin,
      sym__block_quote_begin,
      ts_builtin_sym_end,
    ACTIONS(167), 7,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      sym_verbatim,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1017] = 2,
    ACTIONS(191), 3,
      sym__div_marker_begin,
      sym__block_quote_begin,
      ts_builtin_sym_end,
    ACTIONS(193), 7,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      sym_verbatim,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1032] = 2,
    ACTIONS(195), 3,
      sym__div_marker_begin,
      sym__block_quote_begin,
      ts_builtin_sym_end,
    ACTIONS(197), 7,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      sym_verbatim,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1047] = 5,
    ACTIONS(199), 1,
      anon_sym_LF,
    ACTIONS(204), 1,
      anon_sym__,
    ACTIONS(207), 1,
      anon_sym_STAR,
    ACTIONS(201), 2,
      sym_verbatim,
      sym__text,
    STATE(32), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
  [1068] = 2,
    ACTIONS(210), 3,
      sym__div_marker_begin,
      sym__block_quote_begin,
      ts_builtin_sym_end,
    ACTIONS(212), 7,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      sym_verbatim,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1083] = 5,
    ACTIONS(13), 1,
      anon_sym__,
    ACTIONS(15), 1,
      anon_sym_STAR,
    STATE(18), 1,
      aux_sym_heading_repeat1,
    ACTIONS(11), 2,
      sym_verbatim,
      sym__text,
    STATE(38), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
  [1104] = 5,
    ACTIONS(13), 1,
      anon_sym__,
    ACTIONS(15), 1,
      anon_sym_STAR,
    STATE(17), 1,
      aux_sym_heading_repeat1,
    ACTIONS(11), 2,
      sym_verbatim,
      sym__text,
    STATE(38), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
  [1125] = 5,
    ACTIONS(214), 1,
      anon_sym_LF,
    ACTIONS(219), 1,
      anon_sym__,
    ACTIONS(222), 1,
      anon_sym_STAR,
    ACTIONS(216), 2,
      sym_verbatim,
      sym__text,
    STATE(60), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
  [1146] = 5,
    ACTIONS(225), 1,
      anon_sym_LF,
    ACTIONS(230), 1,
      anon_sym__,
    ACTIONS(233), 1,
      anon_sym_STAR,
    ACTIONS(227), 2,
      sym_verbatim,
      sym__text,
    STATE(59), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
  [1167] = 5,
    ACTIONS(13), 1,
      anon_sym__,
    ACTIONS(15), 1,
      anon_sym_STAR,
    ACTIONS(236), 1,
      anon_sym_LF,
    ACTIONS(238), 2,
      sym_verbatim,
      sym__text,
    STATE(32), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
  [1188] = 2,
    ACTIONS(242), 3,
      sym__block_close,
      sym__div_marker_begin,
      sym__block_quote_begin,
    ACTIONS(240), 7,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      sym_verbatim,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1203] = 2,
    ACTIONS(246), 3,
      sym__block_close,
      sym__div_marker_begin,
      sym__block_quote_begin,
    ACTIONS(244), 7,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      sym_verbatim,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1218] = 2,
    ACTIONS(248), 3,
      sym__div_marker_begin,
      sym__block_quote_begin,
      ts_builtin_sym_end,
    ACTIONS(250), 7,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      sym_verbatim,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1233] = 2,
    ACTIONS(252), 3,
      sym__div_marker_begin,
      sym__block_quote_begin,
      ts_builtin_sym_end,
    ACTIONS(254), 7,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      sym_verbatim,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1248] = 2,
    ACTIONS(256), 3,
      sym__div_marker_begin,
      sym__block_quote_begin,
      ts_builtin_sym_end,
    ACTIONS(258), 7,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      sym_verbatim,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1263] = 2,
    ACTIONS(195), 3,
      sym__block_close,
      sym__div_marker_begin,
      sym__block_quote_begin,
    ACTIONS(197), 7,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      sym_verbatim,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1278] = 2,
    ACTIONS(260), 3,
      sym__div_marker_begin,
      sym__block_quote_begin,
      ts_builtin_sym_end,
    ACTIONS(262), 7,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      sym_verbatim,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1293] = 2,
    ACTIONS(173), 3,
      sym__block_close,
      sym__div_marker_begin,
      sym__block_quote_begin,
    ACTIONS(175), 7,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      sym_verbatim,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1308] = 2,
    ACTIONS(191), 3,
      sym__block_close,
      sym__div_marker_begin,
      sym__block_quote_begin,
    ACTIONS(193), 7,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      sym_verbatim,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1323] = 2,
    ACTIONS(181), 3,
      sym__block_close,
      sym__div_marker_begin,
      sym__block_quote_begin,
    ACTIONS(183), 7,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      sym_verbatim,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1338] = 2,
    ACTIONS(181), 3,
      sym__div_marker_begin,
      sym__block_quote_begin,
      ts_builtin_sym_end,
    ACTIONS(183), 7,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      sym_verbatim,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1353] = 2,
    ACTIONS(256), 3,
      sym__block_close,
      sym__div_marker_begin,
      sym__block_quote_begin,
    ACTIONS(258), 7,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      sym_verbatim,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1368] = 2,
    ACTIONS(252), 3,
      sym__block_close,
      sym__div_marker_begin,
      sym__block_quote_begin,
    ACTIONS(254), 7,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      sym_verbatim,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1383] = 2,
    ACTIONS(248), 3,
      sym__block_close,
      sym__div_marker_begin,
      sym__block_quote_begin,
    ACTIONS(250), 7,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      sym_verbatim,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1398] = 2,
    ACTIONS(210), 3,
      sym__block_close,
      sym__div_marker_begin,
      sym__block_quote_begin,
    ACTIONS(212), 7,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      sym_verbatim,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1413] = 2,
    ACTIONS(260), 3,
      sym__block_close,
      sym__div_marker_begin,
      sym__block_quote_begin,
    ACTIONS(262), 7,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      sym_verbatim,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1428] = 2,
    ACTIONS(242), 3,
      sym__div_marker_begin,
      sym__block_quote_begin,
      ts_builtin_sym_end,
    ACTIONS(240), 7,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      sym_verbatim,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1443] = 2,
    ACTIONS(173), 3,
      sym__div_marker_begin,
      sym__block_quote_begin,
      ts_builtin_sym_end,
    ACTIONS(175), 7,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      sym_verbatim,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1458] = 2,
    ACTIONS(246), 3,
      sym__div_marker_begin,
      sym__block_quote_begin,
      ts_builtin_sym_end,
    ACTIONS(244), 7,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      sym_verbatim,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1473] = 7,
    ACTIONS(264), 1,
      aux_sym_attributes_token1,
    ACTIONS(266), 1,
      anon_sym_RBRACE,
    ACTIONS(268), 1,
      anon_sym_POUND,
    ACTIONS(270), 1,
      anon_sym_DOT,
    ACTIONS(272), 1,
      sym_attribute_key,
    STATE(64), 1,
      aux_sym_attributes_repeat1,
    STATE(73), 3,
      sym_attribute_id,
      sym_attribute_class,
      sym_attribute_key_value,
  [1497] = 4,
    ACTIONS(13), 1,
      anon_sym__,
    ACTIONS(274), 1,
      anon_sym_STAR,
    ACTIONS(238), 2,
      sym_verbatim,
      sym__text,
    STATE(32), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
  [1515] = 4,
    ACTIONS(15), 1,
      anon_sym_STAR,
    ACTIONS(276), 1,
      anon_sym__,
    ACTIONS(238), 2,
      sym_verbatim,
      sym__text,
    STATE(32), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
  [1533] = 7,
    ACTIONS(268), 1,
      anon_sym_POUND,
    ACTIONS(270), 1,
      anon_sym_DOT,
    ACTIONS(272), 1,
      sym_attribute_key,
    ACTIONS(278), 1,
      aux_sym_attributes_token1,
    ACTIONS(280), 1,
      anon_sym_RBRACE,
    STATE(67), 1,
      aux_sym_attributes_repeat1,
    STATE(73), 3,
      sym_attribute_id,
      sym_attribute_class,
      sym_attribute_key_value,
  [1557] = 6,
    ACTIONS(282), 1,
      anon_sym_RBRACE,
    ACTIONS(284), 1,
      anon_sym_POUND,
    ACTIONS(286), 1,
      anon_sym_DOT,
    ACTIONS(288), 1,
      sym_attribute_key,
    STATE(63), 1,
      aux_sym_attributes_repeat1,
    STATE(73), 3,
      sym_attribute_id,
      sym_attribute_class,
      sym_attribute_key_value,
  [1578] = 6,
    ACTIONS(290), 1,
      anon_sym_RBRACE,
    ACTIONS(292), 1,
      anon_sym_POUND,
    ACTIONS(295), 1,
      anon_sym_DOT,
    ACTIONS(298), 1,
      sym_attribute_key,
    STATE(63), 1,
      aux_sym_attributes_repeat1,
    STATE(73), 3,
      sym_attribute_id,
      sym_attribute_class,
      sym_attribute_key_value,
  [1599] = 6,
    ACTIONS(284), 1,
      anon_sym_POUND,
    ACTIONS(286), 1,
      anon_sym_DOT,
    ACTIONS(288), 1,
      sym_attribute_key,
    ACTIONS(301), 1,
      anon_sym_RBRACE,
    STATE(63), 1,
      aux_sym_attributes_repeat1,
    STATE(73), 3,
      sym_attribute_id,
      sym_attribute_class,
      sym_attribute_key_value,
  [1620] = 6,
    ACTIONS(284), 1,
      anon_sym_POUND,
    ACTIONS(286), 1,
      anon_sym_DOT,
    ACTIONS(288), 1,
      sym_attribute_key,
    ACTIONS(301), 1,
      anon_sym_RBRACE,
    STATE(62), 1,
      aux_sym_attributes_repeat1,
    STATE(73), 3,
      sym_attribute_id,
      sym_attribute_class,
      sym_attribute_key_value,
  [1641] = 6,
    ACTIONS(284), 1,
      anon_sym_POUND,
    ACTIONS(286), 1,
      anon_sym_DOT,
    ACTIONS(288), 1,
      sym_attribute_key,
    ACTIONS(303), 1,
      anon_sym_RBRACE,
    STATE(68), 1,
      aux_sym_attributes_repeat1,
    STATE(73), 3,
      sym_attribute_id,
      sym_attribute_class,
      sym_attribute_key_value,
  [1662] = 6,
    ACTIONS(284), 1,
      anon_sym_POUND,
    ACTIONS(286), 1,
      anon_sym_DOT,
    ACTIONS(288), 1,
      sym_attribute_key,
    ACTIONS(303), 1,
      anon_sym_RBRACE,
    STATE(63), 1,
      aux_sym_attributes_repeat1,
    STATE(73), 3,
      sym_attribute_id,
      sym_attribute_class,
      sym_attribute_key_value,
  [1683] = 6,
    ACTIONS(284), 1,
      anon_sym_POUND,
    ACTIONS(286), 1,
      anon_sym_DOT,
    ACTIONS(288), 1,
      sym_attribute_key,
    ACTIONS(305), 1,
      anon_sym_RBRACE,
    STATE(63), 1,
      aux_sym_attributes_repeat1,
    STATE(73), 3,
      sym_attribute_id,
      sym_attribute_class,
      sym_attribute_key_value,
  [1704] = 2,
    ACTIONS(151), 1,
      sym__close_paragraph,
    ACTIONS(140), 5,
      anon_sym_LF,
      sym_verbatim,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1715] = 2,
    ACTIONS(307), 1,
      aux_sym_attributes_token1,
    ACTIONS(309), 4,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_DOT,
      sym_attribute_key,
  [1725] = 1,
    ACTIONS(311), 5,
      anon_sym_LF,
      sym_verbatim,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1733] = 1,
    ACTIONS(313), 5,
      anon_sym_LF,
      sym_verbatim,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1741] = 2,
    ACTIONS(315), 1,
      aux_sym_attributes_token1,
    ACTIONS(317), 4,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_DOT,
      sym_attribute_key,
  [1751] = 2,
    ACTIONS(319), 1,
      aux_sym_attributes_token1,
    ACTIONS(321), 4,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_DOT,
      sym_attribute_key,
  [1761] = 1,
    ACTIONS(323), 5,
      anon_sym_LF,
      sym_verbatim,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1769] = 1,
    ACTIONS(325), 5,
      anon_sym_LF,
      sym_verbatim,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1777] = 1,
    ACTIONS(327), 5,
      anon_sym_LF,
      sym_verbatim,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1785] = 2,
    ACTIONS(329), 1,
      aux_sym_attributes_token1,
    ACTIONS(331), 4,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_DOT,
      sym_attribute_key,
  [1795] = 4,
    ACTIONS(333), 1,
      anon_sym_LF,
    ACTIONS(335), 1,
      anon_sym_LBRACE,
    ACTIONS(337), 1,
      sym_language,
    STATE(109), 1,
      sym_attributes,
  [1808] = 4,
    ACTIONS(339), 1,
      sym_code_block_marker,
    ACTIONS(341), 1,
      aux_sym_code_token1,
    STATE(90), 1,
      aux_sym_code_repeat1,
    STATE(102), 1,
      sym_code,
  [1821] = 4,
    ACTIONS(341), 1,
      aux_sym_code_token1,
    ACTIONS(343), 1,
      sym_code_block_marker,
    STATE(90), 1,
      aux_sym_code_repeat1,
    STATE(111), 1,
      sym_code,
  [1834] = 4,
    ACTIONS(335), 1,
      anon_sym_LBRACE,
    ACTIONS(345), 1,
      anon_sym_LF,
    ACTIONS(347), 1,
      sym_language,
    STATE(114), 1,
      sym_attributes,
  [1847] = 4,
    ACTIONS(341), 1,
      aux_sym_code_token1,
    ACTIONS(349), 1,
      sym_code_block_marker,
    STATE(90), 1,
      aux_sym_code_repeat1,
    STATE(100), 1,
      sym_code,
  [1860] = 4,
    ACTIONS(341), 1,
      aux_sym_code_token1,
    ACTIONS(351), 1,
      sym_code_block_marker,
    STATE(90), 1,
      aux_sym_code_repeat1,
    STATE(108), 1,
      sym_code,
  [1873] = 1,
    ACTIONS(290), 4,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_DOT,
      sym_attribute_key,
  [1880] = 4,
    ACTIONS(341), 1,
      aux_sym_code_token1,
    ACTIONS(353), 1,
      sym_code_block_marker,
    STATE(90), 1,
      aux_sym_code_repeat1,
    STATE(106), 1,
      sym_code,
  [1893] = 4,
    ACTIONS(341), 1,
      aux_sym_code_token1,
    ACTIONS(355), 1,
      sym_code_block_marker,
    STATE(90), 1,
      aux_sym_code_repeat1,
    STATE(104), 1,
      sym_code,
  [1906] = 3,
    ACTIONS(335), 1,
      anon_sym_LBRACE,
    ACTIONS(357), 1,
      anon_sym_LF,
    STATE(115), 1,
      sym_attributes,
  [1916] = 3,
    ACTIONS(335), 1,
      anon_sym_LBRACE,
    ACTIONS(359), 1,
      anon_sym_LF,
    STATE(107), 1,
      sym_attributes,
  [1926] = 3,
    ACTIONS(341), 1,
      aux_sym_code_token1,
    ACTIONS(361), 1,
      sym_code_block_marker,
    STATE(93), 1,
      aux_sym_code_repeat1,
  [1936] = 3,
    ACTIONS(335), 1,
      anon_sym_LBRACE,
    ACTIONS(363), 1,
      anon_sym_LF,
    STATE(112), 1,
      sym_attributes,
  [1946] = 3,
    ACTIONS(335), 1,
      anon_sym_LBRACE,
    ACTIONS(365), 1,
      anon_sym_LF,
    STATE(113), 1,
      sym_attributes,
  [1956] = 3,
    ACTIONS(367), 1,
      sym_code_block_marker,
    ACTIONS(369), 1,
      aux_sym_code_token1,
    STATE(93), 1,
      aux_sym_code_repeat1,
  [1966] = 1,
    ACTIONS(372), 2,
      sym_attribute_value_quoted,
      sym_attribute_value_unquoted,
  [1971] = 1,
    ACTIONS(367), 2,
      sym_code_block_marker,
      aux_sym_code_token1,
  [1976] = 1,
    ACTIONS(374), 1,
      anon_sym_LF,
  [1980] = 1,
    ACTIONS(376), 1,
      anon_sym_LF,
  [1984] = 1,
    ACTIONS(378), 1,
      aux_sym_attribute_id_token1,
  [1988] = 1,
    ACTIONS(380), 1,
      anon_sym_EQ,
  [1992] = 1,
    ACTIONS(382), 1,
      sym_code_block_marker,
  [1996] = 1,
    ACTIONS(384), 1,
      ts_builtin_sym_end,
  [2000] = 1,
    ACTIONS(386), 1,
      sym_code_block_marker,
  [2004] = 1,
    ACTIONS(388), 1,
      anon_sym_LF,
  [2008] = 1,
    ACTIONS(390), 1,
      sym_code_block_marker,
  [2012] = 1,
    ACTIONS(392), 1,
      aux_sym_attribute_id_token1,
  [2016] = 1,
    ACTIONS(394), 1,
      sym_code_block_marker,
  [2020] = 1,
    ACTIONS(396), 1,
      anon_sym_LF,
  [2024] = 1,
    ACTIONS(398), 1,
      sym_code_block_marker,
  [2028] = 1,
    ACTIONS(365), 1,
      anon_sym_LF,
  [2032] = 1,
    ACTIONS(400), 1,
      anon_sym_LF,
  [2036] = 1,
    ACTIONS(402), 1,
      sym_code_block_marker,
  [2040] = 1,
    ACTIONS(404), 1,
      anon_sym_LF,
  [2044] = 1,
    ACTIONS(406), 1,
      anon_sym_LF,
  [2048] = 1,
    ACTIONS(357), 1,
      anon_sym_LF,
  [2052] = 1,
    ACTIONS(408), 1,
      anon_sym_LF,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 48,
  [SMALL_STATE(4)] = 96,
  [SMALL_STATE(5)] = 144,
  [SMALL_STATE(6)] = 192,
  [SMALL_STATE(7)] = 240,
  [SMALL_STATE(8)] = 288,
  [SMALL_STATE(9)] = 336,
  [SMALL_STATE(10)] = 384,
  [SMALL_STATE(11)] = 432,
  [SMALL_STATE(12)] = 480,
  [SMALL_STATE(13)] = 528,
  [SMALL_STATE(14)] = 576,
  [SMALL_STATE(15)] = 624,
  [SMALL_STATE(16)] = 672,
  [SMALL_STATE(17)] = 720,
  [SMALL_STATE(18)] = 747,
  [SMALL_STATE(19)] = 774,
  [SMALL_STATE(20)] = 801,
  [SMALL_STATE(21)] = 828,
  [SMALL_STATE(22)] = 855,
  [SMALL_STATE(23)] = 882,
  [SMALL_STATE(24)] = 909,
  [SMALL_STATE(25)] = 927,
  [SMALL_STATE(26)] = 945,
  [SMALL_STATE(27)] = 963,
  [SMALL_STATE(28)] = 981,
  [SMALL_STATE(29)] = 999,
  [SMALL_STATE(30)] = 1017,
  [SMALL_STATE(31)] = 1032,
  [SMALL_STATE(32)] = 1047,
  [SMALL_STATE(33)] = 1068,
  [SMALL_STATE(34)] = 1083,
  [SMALL_STATE(35)] = 1104,
  [SMALL_STATE(36)] = 1125,
  [SMALL_STATE(37)] = 1146,
  [SMALL_STATE(38)] = 1167,
  [SMALL_STATE(39)] = 1188,
  [SMALL_STATE(40)] = 1203,
  [SMALL_STATE(41)] = 1218,
  [SMALL_STATE(42)] = 1233,
  [SMALL_STATE(43)] = 1248,
  [SMALL_STATE(44)] = 1263,
  [SMALL_STATE(45)] = 1278,
  [SMALL_STATE(46)] = 1293,
  [SMALL_STATE(47)] = 1308,
  [SMALL_STATE(48)] = 1323,
  [SMALL_STATE(49)] = 1338,
  [SMALL_STATE(50)] = 1353,
  [SMALL_STATE(51)] = 1368,
  [SMALL_STATE(52)] = 1383,
  [SMALL_STATE(53)] = 1398,
  [SMALL_STATE(54)] = 1413,
  [SMALL_STATE(55)] = 1428,
  [SMALL_STATE(56)] = 1443,
  [SMALL_STATE(57)] = 1458,
  [SMALL_STATE(58)] = 1473,
  [SMALL_STATE(59)] = 1497,
  [SMALL_STATE(60)] = 1515,
  [SMALL_STATE(61)] = 1533,
  [SMALL_STATE(62)] = 1557,
  [SMALL_STATE(63)] = 1578,
  [SMALL_STATE(64)] = 1599,
  [SMALL_STATE(65)] = 1620,
  [SMALL_STATE(66)] = 1641,
  [SMALL_STATE(67)] = 1662,
  [SMALL_STATE(68)] = 1683,
  [SMALL_STATE(69)] = 1704,
  [SMALL_STATE(70)] = 1715,
  [SMALL_STATE(71)] = 1725,
  [SMALL_STATE(72)] = 1733,
  [SMALL_STATE(73)] = 1741,
  [SMALL_STATE(74)] = 1751,
  [SMALL_STATE(75)] = 1761,
  [SMALL_STATE(76)] = 1769,
  [SMALL_STATE(77)] = 1777,
  [SMALL_STATE(78)] = 1785,
  [SMALL_STATE(79)] = 1795,
  [SMALL_STATE(80)] = 1808,
  [SMALL_STATE(81)] = 1821,
  [SMALL_STATE(82)] = 1834,
  [SMALL_STATE(83)] = 1847,
  [SMALL_STATE(84)] = 1860,
  [SMALL_STATE(85)] = 1873,
  [SMALL_STATE(86)] = 1880,
  [SMALL_STATE(87)] = 1893,
  [SMALL_STATE(88)] = 1906,
  [SMALL_STATE(89)] = 1916,
  [SMALL_STATE(90)] = 1926,
  [SMALL_STATE(91)] = 1936,
  [SMALL_STATE(92)] = 1946,
  [SMALL_STATE(93)] = 1956,
  [SMALL_STATE(94)] = 1966,
  [SMALL_STATE(95)] = 1971,
  [SMALL_STATE(96)] = 1976,
  [SMALL_STATE(97)] = 1980,
  [SMALL_STATE(98)] = 1984,
  [SMALL_STATE(99)] = 1988,
  [SMALL_STATE(100)] = 1992,
  [SMALL_STATE(101)] = 1996,
  [SMALL_STATE(102)] = 2000,
  [SMALL_STATE(103)] = 2004,
  [SMALL_STATE(104)] = 2008,
  [SMALL_STATE(105)] = 2012,
  [SMALL_STATE(106)] = 2016,
  [SMALL_STATE(107)] = 2020,
  [SMALL_STATE(108)] = 2024,
  [SMALL_STATE(109)] = 2028,
  [SMALL_STATE(110)] = 2032,
  [SMALL_STATE(111)] = 2036,
  [SMALL_STATE(112)] = 2040,
  [SMALL_STATE(113)] = 2044,
  [SMALL_STATE(114)] = 2048,
  [SMALL_STATE(115)] = 2052,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [69] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [72] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [75] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [78] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [81] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [84] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [87] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(89),
  [90] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [93] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [96] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [99] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(82),
  [102] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(91),
  [105] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [108] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [112] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [116] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_emphasis, 3, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [124] = {.entry = {.count = 3, .reusable = false}}, REDUCE(sym__fallback, 1, -100, 0), REDUCE(sym_emphasis, 3, 0, 0), SHIFT(60),
  [128] = {.entry = {.count = 3, .reusable = false}}, REDUCE(sym__fallback, 1, -100, 0), REDUCE(sym_emphasis, 3, 0, 0), SHIFT(36),
  [132] = {.entry = {.count = 3, .reusable = false}}, REDUCE(sym__fallback, 1, -100, 0), REDUCE(sym_emphasis, 3, 0, 0), SHIFT(37),
  [136] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_heading_repeat1, 2, 0, 0),
  [142] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_heading_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [145] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_heading_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [148] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_heading_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_heading_repeat1, 2, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_strong_emphasis, 3, 0, 0),
  [155] = {.entry = {.count = 3, .reusable = false}}, REDUCE(sym__fallback_star, 1, -100, 0), REDUCE(sym_strong_emphasis, 3, 0, 0), SHIFT(59),
  [159] = {.entry = {.count = 3, .reusable = false}}, REDUCE(sym__fallback_star, 1, -100, 0), REDUCE(sym_strong_emphasis, 3, 0, 0), SHIFT(36),
  [163] = {.entry = {.count = 3, .reusable = false}}, REDUCE(sym__fallback_star, 1, -100, 0), REDUCE(sym_strong_emphasis, 3, 0, 0), SHIFT(37),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_div, 3, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_div, 3, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_div, 5, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_div, 5, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_div, 4, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_div, 4, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block, 4, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_block, 4, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block, 5, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_block, 5, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__inline, 2, 0, 0),
  [201] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__inline, 2, 0, 0), SHIFT_REPEAT(32),
  [204] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__inline, 2, 0, 0), SHIFT_REPEAT(36),
  [207] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__inline, 2, 0, 0), SHIFT_REPEAT(37),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 2, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paragraph, 2, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__fallback, 1, -100, 0),
  [216] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym__fallback, 1, -100, 0), SHIFT(60),
  [219] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym__fallback, 1, -100, 0), SHIFT(36),
  [222] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym__fallback, 1, -100, 0), SHIFT(37),
  [225] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__fallback_star, 1, -100, 0),
  [227] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym__fallback_star, 1, -100, 0), SHIFT(59),
  [230] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym__fallback_star, 1, -100, 0), SHIFT(36),
  [233] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym__fallback_star, 1, -100, 0), SHIFT(37),
  [236] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [238] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [240] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_block, 6, 0, 0),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block, 6, 0, 0),
  [244] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_div, 6, 0, 0),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_div, 6, 0, 0),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_quote, 3, 0, 0),
  [250] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_quote, 3, 0, 0),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading, 3, 0, 0),
  [254] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heading, 3, 0, 0),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block, 3, 0, 0),
  [258] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_block, 3, 0, 0),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_quote, 2, 0, 0),
  [262] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_quote, 2, 0, 0),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [266] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [268] = {.entry = {.count = 1, .reusable = false}}, SHIFT(105),
  [270] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [272] = {.entry = {.count = 1, .reusable = false}}, SHIFT(99),
  [274] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [276] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [280] = {.entry = {.count = 1, .reusable = false}}, SHIFT(110),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [290] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_attributes_repeat1, 2, 0, 0),
  [292] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_attributes_repeat1, 2, 0, 0), SHIFT_REPEAT(105),
  [295] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_attributes_repeat1, 2, 0, 0), SHIFT_REPEAT(98),
  [298] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_attributes_repeat1, 2, 0, 0), SHIFT_REPEAT(99),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [307] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_id, 2, 0, 0),
  [309] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute_id, 2, 0, 0),
  [311] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_emphasis, 4, 0, 0),
  [313] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_strong_emphasis, 4, 0, 0),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [317] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_attributes_repeat1, 1, 0, 0),
  [319] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_key_value, 3, 0, 0),
  [321] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute_key_value, 3, 0, 0),
  [323] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attributes, 4, 0, 0),
  [325] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attributes, 3, 0, 0),
  [327] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attributes, 2, 0, 0),
  [329] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_class, 2, 0, 0),
  [331] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute_class, 2, 0, 0),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [339] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [341] = {.entry = {.count = 1, .reusable = false}}, SHIFT(96),
  [343] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [349] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [351] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [353] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [355] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [361] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code, 1, 0, 0),
  [363] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [367] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_code_repeat1, 2, 0, 0),
  [369] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_code_repeat1, 2, 0, 0), SHIFT_REPEAT(96),
  [372] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [374] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [376] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attributes, 3, 0, 0),
  [378] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [380] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [382] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [384] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [386] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [388] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attributes, 4, 0, 0),
  [390] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [392] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [394] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [396] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [398] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [400] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attributes, 2, 0, 0),
  [402] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [404] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [406] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [408] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__close_paragraph = 0,
  ts_external_token__block_close = 1,
  ts_external_token__div_marker_begin = 2,
  ts_external_token__div_marker_end = 3,
  ts_external_token__block_quote_begin = 4,
  ts_external_token__ignored = 5,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__close_paragraph] = sym__close_paragraph,
  [ts_external_token__block_close] = sym__block_close,
  [ts_external_token__div_marker_begin] = sym__div_marker_begin,
  [ts_external_token__div_marker_end] = sym__div_marker_end,
  [ts_external_token__block_quote_begin] = sym__block_quote_begin,
  [ts_external_token__ignored] = sym__ignored,
};

static const bool ts_external_scanner_states[7][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__close_paragraph] = true,
    [ts_external_token__block_close] = true,
    [ts_external_token__div_marker_begin] = true,
    [ts_external_token__div_marker_end] = true,
    [ts_external_token__block_quote_begin] = true,
    [ts_external_token__ignored] = true,
  },
  [2] = {
    [ts_external_token__div_marker_begin] = true,
    [ts_external_token__block_quote_begin] = true,
  },
  [3] = {
    [ts_external_token__block_close] = true,
    [ts_external_token__div_marker_begin] = true,
    [ts_external_token__block_quote_begin] = true,
  },
  [4] = {
    [ts_external_token__close_paragraph] = true,
  },
  [5] = {
    [ts_external_token__block_close] = true,
    [ts_external_token__div_marker_begin] = true,
    [ts_external_token__div_marker_end] = true,
    [ts_external_token__block_quote_begin] = true,
  },
  [6] = {
    [ts_external_token__div_marker_begin] = true,
    [ts_external_token__div_marker_end] = true,
    [ts_external_token__block_quote_begin] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_sdjot_external_scanner_create(void);
void tree_sitter_sdjot_external_scanner_destroy(void *);
bool tree_sitter_sdjot_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_sdjot_external_scanner_serialize(void *, char *);
void tree_sitter_sdjot_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_sdjot(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_sdjot_external_scanner_create,
      tree_sitter_sdjot_external_scanner_destroy,
      tree_sitter_sdjot_external_scanner_scan,
      tree_sitter_sdjot_external_scanner_serialize,
      tree_sitter_sdjot_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
