#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 116
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 46
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 6
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  anon_sym_LBRACE = 2,
  aux_sym_attributes_token1 = 3,
  anon_sym_RBRACE = 4,
  anon_sym_POUND = 5,
  aux_sym_attribute_id_token1 = 6,
  anon_sym_DOT = 7,
  anon_sym_EQ = 8,
  sym_attribute_key = 9,
  sym_attribute_value_quoted = 10,
  sym_attribute_value_unquoted = 11,
  sym_heading_marker = 12,
  sym_code_block_marker = 13,
  aux_sym_code_token1 = 14,
  sym_language = 15,
  anon_sym__ = 16,
  anon_sym_STAR = 17,
  sym__text = 18,
  sym__close_paragraph = 19,
  sym__block_close = 20,
  sym__div_marker_begin = 21,
  sym__div_marker_end = 22,
  sym__block_quote_begin = 23,
  sym__ignored = 24,
  sym_document = 25,
  sym__block = 26,
  sym_attributes = 27,
  sym_attribute_id = 28,
  sym_attribute_class = 29,
  sym_attribute_key_value = 30,
  sym_heading = 31,
  sym_block_quote = 32,
  sym_div = 33,
  sym_code_block = 34,
  sym_code = 35,
  sym_paragraph = 36,
  aux_sym__inline = 37,
  sym_emphasis = 38,
  sym_strong_emphasis = 39,
  sym__fallback = 40,
  sym__fallback_star = 41,
  aux_sym_document_repeat1 = 42,
  aux_sym_attributes_repeat1 = 43,
  aux_sym_heading_repeat1 = 44,
  aux_sym_code_repeat1 = 45,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [anon_sym_LBRACE] = "{",
  [aux_sym_attributes_token1] = "attributes_token1",
  [anon_sym_RBRACE] = "}",
  [anon_sym_POUND] = "#",
  [aux_sym_attribute_id_token1] = "attribute_id_token1",
  [anon_sym_DOT] = ".",
  [anon_sym_EQ] = "=",
  [sym_attribute_key] = "attribute_key",
  [sym_attribute_value_quoted] = "attribute_value_quoted",
  [sym_attribute_value_unquoted] = "attribute_value_unquoted",
  [sym_heading_marker] = "heading_marker",
  [sym_code_block_marker] = "code_block_marker",
  [aux_sym_code_token1] = "code_token1",
  [sym_language] = "language",
  [anon_sym__] = "_",
  [anon_sym_STAR] = "*",
  [sym__text] = "_text",
  [sym__close_paragraph] = "_close_paragraph",
  [sym__block_close] = "_block_close",
  [sym__div_marker_begin] = "div_marker",
  [sym__div_marker_end] = "div_marker",
  [sym__block_quote_begin] = "_block_quote_begin",
  [sym__ignored] = "_ignored",
  [sym_document] = "document",
  [sym__block] = "_block",
  [sym_attributes] = "attributes",
  [sym_attribute_id] = "attribute_id",
  [sym_attribute_class] = "attribute_class",
  [sym_attribute_key_value] = "attribute_key_value",
  [sym_heading] = "heading",
  [sym_block_quote] = "block_quote",
  [sym_div] = "div",
  [sym_code_block] = "code_block",
  [sym_code] = "code",
  [sym_paragraph] = "paragraph",
  [aux_sym__inline] = "_inline",
  [sym_emphasis] = "emphasis",
  [sym_strong_emphasis] = "strong_emphasis",
  [sym__fallback] = "_fallback",
  [sym__fallback_star] = "_fallback_star",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_attributes_repeat1] = "attributes_repeat1",
  [aux_sym_heading_repeat1] = "heading_repeat1",
  [aux_sym_code_repeat1] = "code_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [aux_sym_attributes_token1] = aux_sym_attributes_token1,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_attribute_id_token1] = aux_sym_attribute_id_token1,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_attribute_key] = sym_attribute_key,
  [sym_attribute_value_quoted] = sym_attribute_value_quoted,
  [sym_attribute_value_unquoted] = sym_attribute_value_unquoted,
  [sym_heading_marker] = sym_heading_marker,
  [sym_code_block_marker] = sym_code_block_marker,
  [aux_sym_code_token1] = aux_sym_code_token1,
  [sym_language] = sym_language,
  [anon_sym__] = anon_sym__,
  [anon_sym_STAR] = anon_sym_STAR,
  [sym__text] = sym__text,
  [sym__close_paragraph] = sym__close_paragraph,
  [sym__block_close] = sym__block_close,
  [sym__div_marker_begin] = sym__div_marker_begin,
  [sym__div_marker_end] = sym__div_marker_begin,
  [sym__block_quote_begin] = sym__block_quote_begin,
  [sym__ignored] = sym__ignored,
  [sym_document] = sym_document,
  [sym__block] = sym__block,
  [sym_attributes] = sym_attributes,
  [sym_attribute_id] = sym_attribute_id,
  [sym_attribute_class] = sym_attribute_class,
  [sym_attribute_key_value] = sym_attribute_key_value,
  [sym_heading] = sym_heading,
  [sym_block_quote] = sym_block_quote,
  [sym_div] = sym_div,
  [sym_code_block] = sym_code_block,
  [sym_code] = sym_code,
  [sym_paragraph] = sym_paragraph,
  [aux_sym__inline] = aux_sym__inline,
  [sym_emphasis] = sym_emphasis,
  [sym_strong_emphasis] = sym_strong_emphasis,
  [sym__fallback] = sym__fallback,
  [sym__fallback_star] = sym__fallback_star,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_attributes_repeat1] = aux_sym_attributes_repeat1,
  [aux_sym_heading_repeat1] = aux_sym_heading_repeat1,
  [aux_sym_code_repeat1] = aux_sym_code_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_attributes_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_attribute_id_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_key] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value_quoted] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value_unquoted] = {
    .visible = true,
    .named = true,
  },
  [sym_heading_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_code_block_marker] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_code_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_language] = {
    .visible = true,
    .named = true,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [sym__text] = {
    .visible = false,
    .named = true,
  },
  [sym__close_paragraph] = {
    .visible = false,
    .named = true,
  },
  [sym__block_close] = {
    .visible = false,
    .named = true,
  },
  [sym__div_marker_begin] = {
    .visible = true,
    .named = true,
  },
  [sym__div_marker_end] = {
    .visible = true,
    .named = true,
  },
  [sym__block_quote_begin] = {
    .visible = false,
    .named = true,
  },
  [sym__ignored] = {
    .visible = false,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__block] = {
    .visible = false,
    .named = true,
  },
  [sym_attributes] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_id] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_class] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_key_value] = {
    .visible = true,
    .named = true,
  },
  [sym_heading] = {
    .visible = true,
    .named = true,
  },
  [sym_block_quote] = {
    .visible = true,
    .named = true,
  },
  [sym_div] = {
    .visible = true,
    .named = true,
  },
  [sym_code_block] = {
    .visible = true,
    .named = true,
  },
  [sym_code] = {
    .visible = true,
    .named = true,
  },
  [sym_paragraph] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__inline] = {
    .visible = false,
    .named = false,
  },
  [sym_emphasis] = {
    .visible = true,
    .named = true,
  },
  [sym_strong_emphasis] = {
    .visible = true,
    .named = true,
  },
  [sym__fallback] = {
    .visible = false,
    .named = true,
  },
  [sym__fallback_star] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_attributes_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_heading_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_code_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 2,
  [7] = 5,
  [8] = 8,
  [9] = 4,
  [10] = 10,
  [11] = 3,
  [12] = 8,
  [13] = 13,
  [14] = 13,
  [15] = 15,
  [16] = 15,
  [17] = 17,
  [18] = 17,
  [19] = 19,
  [20] = 20,
  [21] = 19,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 25,
  [27] = 27,
  [28] = 27,
  [29] = 24,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 34,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 31,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 30,
  [49] = 49,
  [50] = 49,
  [51] = 43,
  [52] = 42,
  [53] = 41,
  [54] = 33,
  [55] = 46,
  [56] = 40,
  [57] = 44,
  [58] = 45,
  [59] = 47,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 60,
  [64] = 64,
  [65] = 61,
  [66] = 66,
  [67] = 66,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 74,
  [82] = 82,
  [83] = 80,
  [84] = 84,
  [85] = 78,
  [86] = 86,
  [87] = 76,
  [88] = 88,
  [89] = 89,
  [90] = 89,
  [91] = 91,
  [92] = 92,
  [93] = 91,
  [94] = 94,
  [95] = 95,
  [96] = 75,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 101,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 103,
  [107] = 79,
  [108] = 108,
  [109] = 109,
  [110] = 108,
  [111] = 111,
  [112] = 97,
  [113] = 82,
  [114] = 109,
  [115] = 104,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(14);
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead == '\r') SKIP(0);
      if (lookahead == '"') ADVANCE(8);
      if (lookahead == '#') ADVANCE(20);
      if (lookahead == '\'') ADVANCE(10);
      if (lookahead == '*') ADVANCE(36);
      if (lookahead == '.') ADVANCE(22);
      if (lookahead == '=') ADVANCE(23);
      if (lookahead == '_') ADVANCE(35);
      if (lookahead == '`') ADVANCE(12);
      if (lookahead == '{') ADVANCE(16);
      if (lookahead == '}') ADVANCE(19);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead == '\r') ADVANCE(39);
      if (lookahead == '*') ADVANCE(36);
      if (lookahead == '_') ADVANCE(35);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead == '\r') ADVANCE(40);
      if (lookahead == '*') ADVANCE(36);
      if (lookahead == '_') ADVANCE(35);
      if (lookahead == '{') ADVANCE(16);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead == '\r') SKIP(3);
      if (lookahead == '{') ADVANCE(16);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(34);
      END_STATE();
    case 4:
      if (lookahead == '\r') ADVANCE(17);
      if (lookahead == '#') ADVANCE(20);
      if (lookahead == '.') ADVANCE(22);
      if (lookahead == '}') ADVANCE(19);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead == ':' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 5:
      if (lookahead == '\r') SKIP(5);
      if (lookahead == '#') ADVANCE(20);
      if (lookahead == '.') ADVANCE(22);
      if (lookahead == '}') ADVANCE(19);
      if (lookahead == ':' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 6:
      if (lookahead == '\r') SKIP(6);
      if (lookahead == '"') ADVANCE(8);
      if (lookahead == '\'') ADVANCE(10);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '}') ADVANCE(26);
      END_STATE();
    case 7:
      if (lookahead == '\r') SKIP(7);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '}') ADVANCE(21);
      END_STATE();
    case 8:
      if (lookahead == '"') ADVANCE(25);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == '#') ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(27);
      END_STATE();
    case 10:
      if (lookahead == '\'') ADVANCE(25);
      if (lookahead != 0) ADVANCE(10);
      END_STATE();
    case 11:
      if (lookahead == '`') ADVANCE(28);
      END_STATE();
    case 12:
      if (lookahead == '`') ADVANCE(11);
      END_STATE();
    case 13:
      if (eof) ADVANCE(14);
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead == '\r') ADVANCE(38);
      if (lookahead == '#') ADVANCE(41);
      if (lookahead == '*') ADVANCE(36);
      if (lookahead == '_') ADVANCE(35);
      if (lookahead == '`') ADVANCE(42);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_attributes_token1);
      if (lookahead == '\r') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(18);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_attributes_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_attribute_id_token1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '}') ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_attribute_key);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_attribute_value_quoted);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_attribute_value_unquoted);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '}') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_heading_marker);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_code_block_marker);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_code_block_marker);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(33);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_code_token1);
      if (lookahead == '\r') ADVANCE(30);
      if (lookahead == '`') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(33);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_code_token1);
      if (lookahead == '`') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(33);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_code_token1);
      if (lookahead == '`') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(33);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_code_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_language);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{') ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym__);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym__text);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == '\r') ADVANCE(38);
      if (lookahead == '#') ADVANCE(41);
      if (lookahead == '*') ADVANCE(36);
      if (lookahead == '_') ADVANCE(35);
      if (lookahead == '`') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == '\r') ADVANCE(39);
      if (lookahead == '*') ADVANCE(36);
      if (lookahead == '_') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == '\r') ADVANCE(40);
      if (lookahead == '*') ADVANCE(36);
      if (lookahead == '_') ADVANCE(35);
      if (lookahead == '{') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == '#') ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(27);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == '`') ADVANCE(11);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 13, .external_lex_state = 2},
  [2] = {.lex_state = 13, .external_lex_state = 3},
  [3] = {.lex_state = 13, .external_lex_state = 3},
  [4] = {.lex_state = 13, .external_lex_state = 3},
  [5] = {.lex_state = 13, .external_lex_state = 3},
  [6] = {.lex_state = 13, .external_lex_state = 3},
  [7] = {.lex_state = 13, .external_lex_state = 3},
  [8] = {.lex_state = 13, .external_lex_state = 3},
  [9] = {.lex_state = 13, .external_lex_state = 3},
  [10] = {.lex_state = 13, .external_lex_state = 2},
  [11] = {.lex_state = 13, .external_lex_state = 3},
  [12] = {.lex_state = 13, .external_lex_state = 3},
  [13] = {.lex_state = 13, .external_lex_state = 3},
  [14] = {.lex_state = 13, .external_lex_state = 3},
  [15] = {.lex_state = 13, .external_lex_state = 2},
  [16] = {.lex_state = 13, .external_lex_state = 3},
  [17] = {.lex_state = 1, .external_lex_state = 4},
  [18] = {.lex_state = 1, .external_lex_state = 4},
  [19] = {.lex_state = 1, .external_lex_state = 4},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 1, .external_lex_state = 4},
  [22] = {.lex_state = 1, .external_lex_state = 4},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 13, .external_lex_state = 5},
  [25] = {.lex_state = 13, .external_lex_state = 6},
  [26] = {.lex_state = 13, .external_lex_state = 5},
  [27] = {.lex_state = 13, .external_lex_state = 6},
  [28] = {.lex_state = 13, .external_lex_state = 5},
  [29] = {.lex_state = 13, .external_lex_state = 6},
  [30] = {.lex_state = 13, .external_lex_state = 2},
  [31] = {.lex_state = 4},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 13, .external_lex_state = 2},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 4},
  [40] = {.lex_state = 13, .external_lex_state = 3},
  [41] = {.lex_state = 13, .external_lex_state = 2},
  [42] = {.lex_state = 13, .external_lex_state = 2},
  [43] = {.lex_state = 13, .external_lex_state = 2},
  [44] = {.lex_state = 13, .external_lex_state = 3},
  [45] = {.lex_state = 13, .external_lex_state = 3},
  [46] = {.lex_state = 13, .external_lex_state = 2},
  [47] = {.lex_state = 13, .external_lex_state = 3},
  [48] = {.lex_state = 13, .external_lex_state = 3},
  [49] = {.lex_state = 13, .external_lex_state = 2},
  [50] = {.lex_state = 13, .external_lex_state = 3},
  [51] = {.lex_state = 13, .external_lex_state = 3},
  [52] = {.lex_state = 13, .external_lex_state = 3},
  [53] = {.lex_state = 13, .external_lex_state = 3},
  [54] = {.lex_state = 13, .external_lex_state = 3},
  [55] = {.lex_state = 13, .external_lex_state = 3},
  [56] = {.lex_state = 13, .external_lex_state = 2},
  [57] = {.lex_state = 13, .external_lex_state = 2},
  [58] = {.lex_state = 13, .external_lex_state = 2},
  [59] = {.lex_state = 13, .external_lex_state = 2},
  [60] = {.lex_state = 5},
  [61] = {.lex_state = 5},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 5},
  [64] = {.lex_state = 1},
  [65] = {.lex_state = 5},
  [66] = {.lex_state = 5},
  [67] = {.lex_state = 5},
  [68] = {.lex_state = 5},
  [69] = {.lex_state = 4},
  [70] = {.lex_state = 1, .external_lex_state = 4},
  [71] = {.lex_state = 4},
  [72] = {.lex_state = 4},
  [73] = {.lex_state = 4},
  [74] = {.lex_state = 30},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 30},
  [77] = {.lex_state = 5},
  [78] = {.lex_state = 30},
  [79] = {.lex_state = 1},
  [80] = {.lex_state = 3},
  [81] = {.lex_state = 30},
  [82] = {.lex_state = 1},
  [83] = {.lex_state = 3},
  [84] = {.lex_state = 1},
  [85] = {.lex_state = 30},
  [86] = {.lex_state = 1},
  [87] = {.lex_state = 30},
  [88] = {.lex_state = 30},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 30},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 6},
  [95] = {.lex_state = 30},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 7},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 7},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_attribute_value_quoted] = ACTIONS(1),
    [sym_code_block_marker] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [sym__close_paragraph] = ACTIONS(1),
    [sym__block_close] = ACTIONS(1),
    [sym__div_marker_begin] = ACTIONS(1),
    [sym__div_marker_end] = ACTIONS(1),
    [sym__block_quote_begin] = ACTIONS(1),
    [sym__ignored] = ACTIONS(1),
  },
  [1] = {
    [sym_document] = STATE(105),
    [sym__block] = STATE(10),
    [sym_heading] = STATE(10),
    [sym_block_quote] = STATE(10),
    [sym_div] = STATE(10),
    [sym_code_block] = STATE(10),
    [sym_paragraph] = STATE(10),
    [aux_sym__inline] = STATE(38),
    [sym_emphasis] = STATE(38),
    [sym_strong_emphasis] = STATE(38),
    [sym__fallback] = STATE(38),
    [sym__fallback_star] = STATE(38),
    [aux_sym_document_repeat1] = STATE(10),
    [aux_sym_heading_repeat1] = STATE(19),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(5),
    [sym_heading_marker] = ACTIONS(7),
    [sym_code_block_marker] = ACTIONS(9),
    [anon_sym__] = ACTIONS(11),
    [anon_sym_STAR] = ACTIONS(13),
    [sym__text] = ACTIONS(15),
    [sym__div_marker_begin] = ACTIONS(17),
    [sym__block_quote_begin] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(11), 1,
      anon_sym__,
    ACTIONS(13), 1,
      anon_sym_STAR,
    ACTIONS(15), 1,
      sym__text,
    ACTIONS(21), 1,
      anon_sym_LF,
    ACTIONS(23), 1,
      sym_heading_marker,
    ACTIONS(25), 1,
      sym_code_block_marker,
    ACTIONS(27), 1,
      sym__block_close,
    ACTIONS(29), 1,
      sym__div_marker_begin,
    ACTIONS(31), 1,
      sym__block_quote_begin,
    STATE(21), 1,
      aux_sym_heading_repeat1,
    STATE(38), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
    STATE(16), 7,
      sym__block,
      sym_heading,
      sym_block_quote,
      sym_div,
      sym_code_block,
      sym_paragraph,
      aux_sym_document_repeat1,
  [47] = 12,
    ACTIONS(11), 1,
      anon_sym__,
    ACTIONS(13), 1,
      anon_sym_STAR,
    ACTIONS(15), 1,
      sym__text,
    ACTIONS(21), 1,
      anon_sym_LF,
    ACTIONS(23), 1,
      sym_heading_marker,
    ACTIONS(25), 1,
      sym_code_block_marker,
    ACTIONS(29), 1,
      sym__div_marker_begin,
    ACTIONS(31), 1,
      sym__block_quote_begin,
    ACTIONS(33), 1,
      sym__block_close,
    STATE(21), 1,
      aux_sym_heading_repeat1,
    STATE(38), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
    STATE(16), 7,
      sym__block,
      sym_heading,
      sym_block_quote,
      sym_div,
      sym_code_block,
      sym_paragraph,
      aux_sym_document_repeat1,
  [94] = 12,
    ACTIONS(11), 1,
      anon_sym__,
    ACTIONS(13), 1,
      anon_sym_STAR,
    ACTIONS(15), 1,
      sym__text,
    ACTIONS(23), 1,
      sym_heading_marker,
    ACTIONS(25), 1,
      sym_code_block_marker,
    ACTIONS(29), 1,
      sym__div_marker_begin,
    ACTIONS(31), 1,
      sym__block_quote_begin,
    ACTIONS(35), 1,
      anon_sym_LF,
    ACTIONS(37), 1,
      sym__block_close,
    STATE(21), 1,
      aux_sym_heading_repeat1,
    STATE(38), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
    STATE(3), 7,
      sym__block,
      sym_heading,
      sym_block_quote,
      sym_div,
      sym_code_block,
      sym_paragraph,
      aux_sym_document_repeat1,
  [141] = 12,
    ACTIONS(11), 1,
      anon_sym__,
    ACTIONS(13), 1,
      anon_sym_STAR,
    ACTIONS(15), 1,
      sym__text,
    ACTIONS(21), 1,
      anon_sym_LF,
    ACTIONS(23), 1,
      sym_heading_marker,
    ACTIONS(25), 1,
      sym_code_block_marker,
    ACTIONS(29), 1,
      sym__div_marker_begin,
    ACTIONS(31), 1,
      sym__block_quote_begin,
    ACTIONS(37), 1,
      sym__block_close,
    STATE(21), 1,
      aux_sym_heading_repeat1,
    STATE(38), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
    STATE(16), 7,
      sym__block,
      sym_heading,
      sym_block_quote,
      sym_div,
      sym_code_block,
      sym_paragraph,
      aux_sym_document_repeat1,
  [188] = 12,
    ACTIONS(11), 1,
      anon_sym__,
    ACTIONS(13), 1,
      anon_sym_STAR,
    ACTIONS(15), 1,
      sym__text,
    ACTIONS(21), 1,
      anon_sym_LF,
    ACTIONS(23), 1,
      sym_heading_marker,
    ACTIONS(25), 1,
      sym_code_block_marker,
    ACTIONS(29), 1,
      sym__div_marker_begin,
    ACTIONS(31), 1,
      sym__block_quote_begin,
    ACTIONS(39), 1,
      sym__block_close,
    STATE(21), 1,
      aux_sym_heading_repeat1,
    STATE(38), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
    STATE(16), 7,
      sym__block,
      sym_heading,
      sym_block_quote,
      sym_div,
      sym_code_block,
      sym_paragraph,
      aux_sym_document_repeat1,
  [235] = 12,
    ACTIONS(11), 1,
      anon_sym__,
    ACTIONS(13), 1,
      anon_sym_STAR,
    ACTIONS(15), 1,
      sym__text,
    ACTIONS(21), 1,
      anon_sym_LF,
    ACTIONS(23), 1,
      sym_heading_marker,
    ACTIONS(25), 1,
      sym_code_block_marker,
    ACTIONS(29), 1,
      sym__div_marker_begin,
    ACTIONS(31), 1,
      sym__block_quote_begin,
    ACTIONS(41), 1,
      sym__block_close,
    STATE(21), 1,
      aux_sym_heading_repeat1,
    STATE(38), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
    STATE(16), 7,
      sym__block,
      sym_heading,
      sym_block_quote,
      sym_div,
      sym_code_block,
      sym_paragraph,
      aux_sym_document_repeat1,
  [282] = 12,
    ACTIONS(11), 1,
      anon_sym__,
    ACTIONS(13), 1,
      anon_sym_STAR,
    ACTIONS(15), 1,
      sym__text,
    ACTIONS(23), 1,
      sym_heading_marker,
    ACTIONS(25), 1,
      sym_code_block_marker,
    ACTIONS(29), 1,
      sym__div_marker_begin,
    ACTIONS(31), 1,
      sym__block_quote_begin,
    ACTIONS(43), 1,
      anon_sym_LF,
    ACTIONS(45), 1,
      sym__block_close,
    STATE(21), 1,
      aux_sym_heading_repeat1,
    STATE(38), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
    STATE(5), 7,
      sym__block,
      sym_heading,
      sym_block_quote,
      sym_div,
      sym_code_block,
      sym_paragraph,
      aux_sym_document_repeat1,
  [329] = 12,
    ACTIONS(11), 1,
      anon_sym__,
    ACTIONS(13), 1,
      anon_sym_STAR,
    ACTIONS(15), 1,
      sym__text,
    ACTIONS(23), 1,
      sym_heading_marker,
    ACTIONS(25), 1,
      sym_code_block_marker,
    ACTIONS(29), 1,
      sym__div_marker_begin,
    ACTIONS(31), 1,
      sym__block_quote_begin,
    ACTIONS(41), 1,
      sym__block_close,
    ACTIONS(47), 1,
      anon_sym_LF,
    STATE(21), 1,
      aux_sym_heading_repeat1,
    STATE(38), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
    STATE(11), 7,
      sym__block,
      sym_heading,
      sym_block_quote,
      sym_div,
      sym_code_block,
      sym_paragraph,
      aux_sym_document_repeat1,
  [376] = 12,
    ACTIONS(7), 1,
      sym_heading_marker,
    ACTIONS(9), 1,
      sym_code_block_marker,
    ACTIONS(11), 1,
      anon_sym__,
    ACTIONS(13), 1,
      anon_sym_STAR,
    ACTIONS(15), 1,
      sym__text,
    ACTIONS(17), 1,
      sym__div_marker_begin,
    ACTIONS(19), 1,
      sym__block_quote_begin,
    ACTIONS(49), 1,
      ts_builtin_sym_end,
    ACTIONS(51), 1,
      anon_sym_LF,
    STATE(19), 1,
      aux_sym_heading_repeat1,
    STATE(38), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
    STATE(15), 7,
      sym__block,
      sym_heading,
      sym_block_quote,
      sym_div,
      sym_code_block,
      sym_paragraph,
      aux_sym_document_repeat1,
  [423] = 12,
    ACTIONS(11), 1,
      anon_sym__,
    ACTIONS(13), 1,
      anon_sym_STAR,
    ACTIONS(15), 1,
      sym__text,
    ACTIONS(21), 1,
      anon_sym_LF,
    ACTIONS(23), 1,
      sym_heading_marker,
    ACTIONS(25), 1,
      sym_code_block_marker,
    ACTIONS(29), 1,
      sym__div_marker_begin,
    ACTIONS(31), 1,
      sym__block_quote_begin,
    ACTIONS(53), 1,
      sym__block_close,
    STATE(21), 1,
      aux_sym_heading_repeat1,
    STATE(38), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
    STATE(16), 7,
      sym__block,
      sym_heading,
      sym_block_quote,
      sym_div,
      sym_code_block,
      sym_paragraph,
      aux_sym_document_repeat1,
  [470] = 12,
    ACTIONS(11), 1,
      anon_sym__,
    ACTIONS(13), 1,
      anon_sym_STAR,
    ACTIONS(15), 1,
      sym__text,
    ACTIONS(23), 1,
      sym_heading_marker,
    ACTIONS(25), 1,
      sym_code_block_marker,
    ACTIONS(29), 1,
      sym__div_marker_begin,
    ACTIONS(31), 1,
      sym__block_quote_begin,
    ACTIONS(55), 1,
      anon_sym_LF,
    ACTIONS(57), 1,
      sym__block_close,
    STATE(21), 1,
      aux_sym_heading_repeat1,
    STATE(38), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
    STATE(7), 7,
      sym__block,
      sym_heading,
      sym_block_quote,
      sym_div,
      sym_code_block,
      sym_paragraph,
      aux_sym_document_repeat1,
  [517] = 12,
    ACTIONS(11), 1,
      anon_sym__,
    ACTIONS(13), 1,
      anon_sym_STAR,
    ACTIONS(15), 1,
      sym__text,
    ACTIONS(23), 1,
      sym_heading_marker,
    ACTIONS(25), 1,
      sym_code_block_marker,
    ACTIONS(29), 1,
      sym__div_marker_begin,
    ACTIONS(31), 1,
      sym__block_quote_begin,
    ACTIONS(59), 1,
      anon_sym_LF,
    ACTIONS(61), 1,
      sym__block_close,
    STATE(21), 1,
      aux_sym_heading_repeat1,
    STATE(38), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
    STATE(2), 7,
      sym__block,
      sym_heading,
      sym_block_quote,
      sym_div,
      sym_code_block,
      sym_paragraph,
      aux_sym_document_repeat1,
  [564] = 12,
    ACTIONS(11), 1,
      anon_sym__,
    ACTIONS(13), 1,
      anon_sym_STAR,
    ACTIONS(15), 1,
      sym__text,
    ACTIONS(23), 1,
      sym_heading_marker,
    ACTIONS(25), 1,
      sym_code_block_marker,
    ACTIONS(29), 1,
      sym__div_marker_begin,
    ACTIONS(31), 1,
      sym__block_quote_begin,
    ACTIONS(63), 1,
      anon_sym_LF,
    ACTIONS(65), 1,
      sym__block_close,
    STATE(21), 1,
      aux_sym_heading_repeat1,
    STATE(38), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
    STATE(6), 7,
      sym__block,
      sym_heading,
      sym_block_quote,
      sym_div,
      sym_code_block,
      sym_paragraph,
      aux_sym_document_repeat1,
  [611] = 12,
    ACTIONS(67), 1,
      ts_builtin_sym_end,
    ACTIONS(69), 1,
      anon_sym_LF,
    ACTIONS(72), 1,
      sym_heading_marker,
    ACTIONS(75), 1,
      sym_code_block_marker,
    ACTIONS(78), 1,
      anon_sym__,
    ACTIONS(81), 1,
      anon_sym_STAR,
    ACTIONS(84), 1,
      sym__text,
    ACTIONS(87), 1,
      sym__div_marker_begin,
    ACTIONS(90), 1,
      sym__block_quote_begin,
    STATE(19), 1,
      aux_sym_heading_repeat1,
    STATE(38), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
    STATE(15), 7,
      sym__block,
      sym_heading,
      sym_block_quote,
      sym_div,
      sym_code_block,
      sym_paragraph,
      aux_sym_document_repeat1,
  [658] = 12,
    ACTIONS(67), 1,
      sym__block_close,
    ACTIONS(78), 1,
      anon_sym__,
    ACTIONS(81), 1,
      anon_sym_STAR,
    ACTIONS(84), 1,
      sym__text,
    ACTIONS(93), 1,
      anon_sym_LF,
    ACTIONS(96), 1,
      sym_heading_marker,
    ACTIONS(99), 1,
      sym_code_block_marker,
    ACTIONS(102), 1,
      sym__div_marker_begin,
    ACTIONS(105), 1,
      sym__block_quote_begin,
    STATE(21), 1,
      aux_sym_heading_repeat1,
    STATE(38), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
    STATE(16), 7,
      sym__block,
      sym_heading,
      sym_block_quote,
      sym_div,
      sym_code_block,
      sym_paragraph,
      aux_sym_document_repeat1,
  [705] = 7,
    ACTIONS(11), 1,
      anon_sym__,
    ACTIONS(13), 1,
      anon_sym_STAR,
    ACTIONS(15), 1,
      sym__text,
    ACTIONS(108), 1,
      anon_sym_LF,
    ACTIONS(110), 1,
      sym__close_paragraph,
    STATE(22), 1,
      aux_sym_heading_repeat1,
    STATE(38), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
  [731] = 7,
    ACTIONS(11), 1,
      anon_sym__,
    ACTIONS(13), 1,
      anon_sym_STAR,
    ACTIONS(15), 1,
      sym__text,
    ACTIONS(112), 1,
      anon_sym_LF,
    ACTIONS(114), 1,
      sym__close_paragraph,
    STATE(22), 1,
      aux_sym_heading_repeat1,
    STATE(38), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
  [757] = 7,
    ACTIONS(11), 1,
      anon_sym__,
    ACTIONS(13), 1,
      anon_sym_STAR,
    ACTIONS(15), 1,
      sym__text,
    ACTIONS(116), 1,
      anon_sym_LF,
    ACTIONS(118), 1,
      sym__close_paragraph,
    STATE(22), 1,
      aux_sym_heading_repeat1,
    STATE(38), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
  [783] = 7,
    ACTIONS(120), 1,
      anon_sym_LF,
    ACTIONS(122), 1,
      anon_sym_LBRACE,
    ACTIONS(124), 1,
      anon_sym__,
    ACTIONS(128), 1,
      anon_sym_STAR,
    ACTIONS(132), 1,
      sym__text,
    STATE(86), 1,
      sym_attributes,
    STATE(64), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
  [809] = 7,
    ACTIONS(11), 1,
      anon_sym__,
    ACTIONS(13), 1,
      anon_sym_STAR,
    ACTIONS(15), 1,
      sym__text,
    ACTIONS(136), 1,
      anon_sym_LF,
    ACTIONS(138), 1,
      sym__close_paragraph,
    STATE(22), 1,
      aux_sym_heading_repeat1,
    STATE(38), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
  [835] = 7,
    ACTIONS(140), 1,
      anon_sym_LF,
    ACTIONS(142), 1,
      anon_sym__,
    ACTIONS(145), 1,
      anon_sym_STAR,
    ACTIONS(148), 1,
      sym__text,
    ACTIONS(151), 1,
      sym__close_paragraph,
    STATE(22), 1,
      aux_sym_heading_repeat1,
    STATE(38), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
  [861] = 7,
    ACTIONS(122), 1,
      anon_sym_LBRACE,
    ACTIONS(153), 1,
      anon_sym_LF,
    ACTIONS(155), 1,
      anon_sym__,
    ACTIONS(159), 1,
      anon_sym_STAR,
    ACTIONS(163), 1,
      sym__text,
    STATE(84), 1,
      sym_attributes,
    STATE(62), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
  [887] = 3,
    ACTIONS(171), 1,
      sym__div_marker_end,
    ACTIONS(169), 3,
      sym__block_close,
      sym__div_marker_begin,
      sym__block_quote_begin,
    ACTIONS(167), 6,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [904] = 3,
    ACTIONS(177), 1,
      sym__div_marker_end,
    ACTIONS(173), 3,
      sym__div_marker_begin,
      sym__block_quote_begin,
      ts_builtin_sym_end,
    ACTIONS(175), 6,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [921] = 3,
    ACTIONS(179), 1,
      sym__div_marker_end,
    ACTIONS(173), 3,
      sym__block_close,
      sym__div_marker_begin,
      sym__block_quote_begin,
    ACTIONS(175), 6,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [938] = 3,
    ACTIONS(185), 1,
      sym__div_marker_end,
    ACTIONS(181), 3,
      sym__div_marker_begin,
      sym__block_quote_begin,
      ts_builtin_sym_end,
    ACTIONS(183), 6,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [955] = 3,
    ACTIONS(187), 1,
      sym__div_marker_end,
    ACTIONS(181), 3,
      sym__block_close,
      sym__div_marker_begin,
      sym__block_quote_begin,
    ACTIONS(183), 6,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [972] = 3,
    ACTIONS(189), 1,
      sym__div_marker_end,
    ACTIONS(169), 3,
      sym__div_marker_begin,
      sym__block_quote_begin,
      ts_builtin_sym_end,
    ACTIONS(167), 6,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [989] = 2,
    ACTIONS(191), 3,
      sym__div_marker_begin,
      sym__block_quote_begin,
      ts_builtin_sym_end,
    ACTIONS(193), 6,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1003] = 7,
    ACTIONS(195), 1,
      aux_sym_attributes_token1,
    ACTIONS(197), 1,
      anon_sym_RBRACE,
    ACTIONS(199), 1,
      anon_sym_POUND,
    ACTIONS(201), 1,
      anon_sym_DOT,
    ACTIONS(203), 1,
      sym_attribute_key,
    STATE(60), 1,
      aux_sym_attributes_repeat1,
    STATE(71), 3,
      sym_attribute_id,
      sym_attribute_class,
      sym_attribute_key_value,
  [1027] = 5,
    ACTIONS(205), 1,
      anon_sym_LF,
    ACTIONS(207), 1,
      anon_sym__,
    ACTIONS(210), 1,
      anon_sym_STAR,
    ACTIONS(213), 1,
      sym__text,
    STATE(32), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
  [1047] = 2,
    ACTIONS(216), 3,
      sym__div_marker_begin,
      sym__block_quote_begin,
      ts_builtin_sym_end,
    ACTIONS(218), 6,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1061] = 5,
    ACTIONS(11), 1,
      anon_sym__,
    ACTIONS(13), 1,
      anon_sym_STAR,
    ACTIONS(15), 1,
      sym__text,
    STATE(18), 1,
      aux_sym_heading_repeat1,
    STATE(38), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
  [1081] = 5,
    ACTIONS(11), 1,
      anon_sym__,
    ACTIONS(13), 1,
      anon_sym_STAR,
    ACTIONS(15), 1,
      sym__text,
    STATE(17), 1,
      aux_sym_heading_repeat1,
    STATE(38), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
  [1101] = 5,
    ACTIONS(220), 1,
      anon_sym_LF,
    ACTIONS(222), 1,
      anon_sym__,
    ACTIONS(225), 1,
      anon_sym_STAR,
    ACTIONS(228), 1,
      sym__text,
    STATE(64), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
  [1121] = 5,
    ACTIONS(231), 1,
      anon_sym_LF,
    ACTIONS(233), 1,
      anon_sym__,
    ACTIONS(236), 1,
      anon_sym_STAR,
    ACTIONS(239), 1,
      sym__text,
    STATE(62), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
  [1141] = 5,
    ACTIONS(11), 1,
      anon_sym__,
    ACTIONS(13), 1,
      anon_sym_STAR,
    ACTIONS(242), 1,
      anon_sym_LF,
    ACTIONS(244), 1,
      sym__text,
    STATE(32), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
  [1161] = 7,
    ACTIONS(199), 1,
      anon_sym_POUND,
    ACTIONS(201), 1,
      anon_sym_DOT,
    ACTIONS(203), 1,
      sym_attribute_key,
    ACTIONS(246), 1,
      aux_sym_attributes_token1,
    ACTIONS(248), 1,
      anon_sym_RBRACE,
    STATE(63), 1,
      aux_sym_attributes_repeat1,
    STATE(71), 3,
      sym_attribute_id,
      sym_attribute_class,
      sym_attribute_key_value,
  [1185] = 2,
    ACTIONS(252), 3,
      sym__block_close,
      sym__div_marker_begin,
      sym__block_quote_begin,
    ACTIONS(250), 6,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1199] = 2,
    ACTIONS(254), 3,
      sym__div_marker_begin,
      sym__block_quote_begin,
      ts_builtin_sym_end,
    ACTIONS(256), 6,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1213] = 2,
    ACTIONS(258), 3,
      sym__div_marker_begin,
      sym__block_quote_begin,
      ts_builtin_sym_end,
    ACTIONS(260), 6,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1227] = 2,
    ACTIONS(262), 3,
      sym__div_marker_begin,
      sym__block_quote_begin,
      ts_builtin_sym_end,
    ACTIONS(264), 6,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1241] = 2,
    ACTIONS(268), 3,
      sym__block_close,
      sym__div_marker_begin,
      sym__block_quote_begin,
    ACTIONS(266), 6,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1255] = 2,
    ACTIONS(272), 3,
      sym__block_close,
      sym__div_marker_begin,
      sym__block_quote_begin,
    ACTIONS(270), 6,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1269] = 2,
    ACTIONS(274), 3,
      sym__div_marker_begin,
      sym__block_quote_begin,
      ts_builtin_sym_end,
    ACTIONS(276), 6,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1283] = 2,
    ACTIONS(173), 3,
      sym__block_close,
      sym__div_marker_begin,
      sym__block_quote_begin,
    ACTIONS(175), 6,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1297] = 2,
    ACTIONS(191), 3,
      sym__block_close,
      sym__div_marker_begin,
      sym__block_quote_begin,
    ACTIONS(193), 6,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1311] = 2,
    ACTIONS(181), 3,
      sym__div_marker_begin,
      sym__block_quote_begin,
      ts_builtin_sym_end,
    ACTIONS(183), 6,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1325] = 2,
    ACTIONS(181), 3,
      sym__block_close,
      sym__div_marker_begin,
      sym__block_quote_begin,
    ACTIONS(183), 6,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1339] = 2,
    ACTIONS(262), 3,
      sym__block_close,
      sym__div_marker_begin,
      sym__block_quote_begin,
    ACTIONS(264), 6,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1353] = 2,
    ACTIONS(258), 3,
      sym__block_close,
      sym__div_marker_begin,
      sym__block_quote_begin,
    ACTIONS(260), 6,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1367] = 2,
    ACTIONS(254), 3,
      sym__block_close,
      sym__div_marker_begin,
      sym__block_quote_begin,
    ACTIONS(256), 6,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1381] = 2,
    ACTIONS(216), 3,
      sym__block_close,
      sym__div_marker_begin,
      sym__block_quote_begin,
    ACTIONS(218), 6,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1395] = 2,
    ACTIONS(274), 3,
      sym__block_close,
      sym__div_marker_begin,
      sym__block_quote_begin,
    ACTIONS(276), 6,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1409] = 2,
    ACTIONS(252), 3,
      sym__div_marker_begin,
      sym__block_quote_begin,
      ts_builtin_sym_end,
    ACTIONS(250), 6,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1423] = 2,
    ACTIONS(268), 3,
      sym__div_marker_begin,
      sym__block_quote_begin,
      ts_builtin_sym_end,
    ACTIONS(266), 6,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1437] = 2,
    ACTIONS(272), 3,
      sym__div_marker_begin,
      sym__block_quote_begin,
      ts_builtin_sym_end,
    ACTIONS(270), 6,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1451] = 2,
    ACTIONS(173), 3,
      sym__div_marker_begin,
      sym__block_quote_begin,
      ts_builtin_sym_end,
    ACTIONS(175), 6,
      anon_sym_LF,
      sym_heading_marker,
      sym_code_block_marker,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1465] = 6,
    ACTIONS(278), 1,
      anon_sym_RBRACE,
    ACTIONS(280), 1,
      anon_sym_POUND,
    ACTIONS(282), 1,
      anon_sym_DOT,
    ACTIONS(284), 1,
      sym_attribute_key,
    STATE(68), 1,
      aux_sym_attributes_repeat1,
    STATE(71), 3,
      sym_attribute_id,
      sym_attribute_class,
      sym_attribute_key_value,
  [1486] = 6,
    ACTIONS(278), 1,
      anon_sym_RBRACE,
    ACTIONS(280), 1,
      anon_sym_POUND,
    ACTIONS(282), 1,
      anon_sym_DOT,
    ACTIONS(284), 1,
      sym_attribute_key,
    STATE(66), 1,
      aux_sym_attributes_repeat1,
    STATE(71), 3,
      sym_attribute_id,
      sym_attribute_class,
      sym_attribute_key_value,
  [1507] = 4,
    ACTIONS(11), 1,
      anon_sym__,
    ACTIONS(244), 1,
      sym__text,
    ACTIONS(286), 1,
      anon_sym_STAR,
    STATE(32), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
  [1524] = 6,
    ACTIONS(280), 1,
      anon_sym_POUND,
    ACTIONS(282), 1,
      anon_sym_DOT,
    ACTIONS(284), 1,
      sym_attribute_key,
    ACTIONS(288), 1,
      anon_sym_RBRACE,
    STATE(68), 1,
      aux_sym_attributes_repeat1,
    STATE(71), 3,
      sym_attribute_id,
      sym_attribute_class,
      sym_attribute_key_value,
  [1545] = 4,
    ACTIONS(13), 1,
      anon_sym_STAR,
    ACTIONS(244), 1,
      sym__text,
    ACTIONS(290), 1,
      anon_sym__,
    STATE(32), 5,
      aux_sym__inline,
      sym_emphasis,
      sym_strong_emphasis,
      sym__fallback,
      sym__fallback_star,
  [1562] = 6,
    ACTIONS(280), 1,
      anon_sym_POUND,
    ACTIONS(282), 1,
      anon_sym_DOT,
    ACTIONS(284), 1,
      sym_attribute_key,
    ACTIONS(288), 1,
      anon_sym_RBRACE,
    STATE(67), 1,
      aux_sym_attributes_repeat1,
    STATE(71), 3,
      sym_attribute_id,
      sym_attribute_class,
      sym_attribute_key_value,
  [1583] = 6,
    ACTIONS(280), 1,
      anon_sym_POUND,
    ACTIONS(282), 1,
      anon_sym_DOT,
    ACTIONS(284), 1,
      sym_attribute_key,
    ACTIONS(292), 1,
      anon_sym_RBRACE,
    STATE(68), 1,
      aux_sym_attributes_repeat1,
    STATE(71), 3,
      sym_attribute_id,
      sym_attribute_class,
      sym_attribute_key_value,
  [1604] = 6,
    ACTIONS(280), 1,
      anon_sym_POUND,
    ACTIONS(282), 1,
      anon_sym_DOT,
    ACTIONS(284), 1,
      sym_attribute_key,
    ACTIONS(294), 1,
      anon_sym_RBRACE,
    STATE(68), 1,
      aux_sym_attributes_repeat1,
    STATE(71), 3,
      sym_attribute_id,
      sym_attribute_class,
      sym_attribute_key_value,
  [1625] = 6,
    ACTIONS(296), 1,
      anon_sym_RBRACE,
    ACTIONS(298), 1,
      anon_sym_POUND,
    ACTIONS(301), 1,
      anon_sym_DOT,
    ACTIONS(304), 1,
      sym_attribute_key,
    STATE(68), 1,
      aux_sym_attributes_repeat1,
    STATE(71), 3,
      sym_attribute_id,
      sym_attribute_class,
      sym_attribute_key_value,
  [1646] = 2,
    ACTIONS(307), 1,
      aux_sym_attributes_token1,
    ACTIONS(309), 4,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_DOT,
      sym_attribute_key,
  [1656] = 2,
    ACTIONS(151), 1,
      sym__close_paragraph,
    ACTIONS(140), 4,
      anon_sym_LF,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1666] = 2,
    ACTIONS(311), 1,
      aux_sym_attributes_token1,
    ACTIONS(313), 4,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_DOT,
      sym_attribute_key,
  [1676] = 2,
    ACTIONS(315), 1,
      aux_sym_attributes_token1,
    ACTIONS(317), 4,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_DOT,
      sym_attribute_key,
  [1686] = 2,
    ACTIONS(319), 1,
      aux_sym_attributes_token1,
    ACTIONS(321), 4,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_DOT,
      sym_attribute_key,
  [1696] = 4,
    ACTIONS(323), 1,
      sym_code_block_marker,
    ACTIONS(325), 1,
      aux_sym_code_token1,
    STATE(92), 1,
      aux_sym_code_repeat1,
    STATE(106), 1,
      sym_code,
  [1709] = 1,
    ACTIONS(327), 4,
      anon_sym_LF,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1716] = 4,
    ACTIONS(325), 1,
      aux_sym_code_token1,
    ACTIONS(329), 1,
      sym_code_block_marker,
    STATE(92), 1,
      aux_sym_code_repeat1,
    STATE(108), 1,
      sym_code,
  [1729] = 1,
    ACTIONS(296), 4,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_DOT,
      sym_attribute_key,
  [1736] = 4,
    ACTIONS(325), 1,
      aux_sym_code_token1,
    ACTIONS(331), 1,
      sym_code_block_marker,
    STATE(92), 1,
      aux_sym_code_repeat1,
    STATE(101), 1,
      sym_code,
  [1749] = 1,
    ACTIONS(333), 4,
      anon_sym_LF,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1756] = 4,
    ACTIONS(335), 1,
      anon_sym_LF,
    ACTIONS(337), 1,
      anon_sym_LBRACE,
    ACTIONS(339), 1,
      sym_language,
    STATE(109), 1,
      sym_attributes,
  [1769] = 4,
    ACTIONS(325), 1,
      aux_sym_code_token1,
    ACTIONS(341), 1,
      sym_code_block_marker,
    STATE(92), 1,
      aux_sym_code_repeat1,
    STATE(103), 1,
      sym_code,
  [1782] = 1,
    ACTIONS(343), 4,
      anon_sym_LF,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1789] = 4,
    ACTIONS(337), 1,
      anon_sym_LBRACE,
    ACTIONS(345), 1,
      anon_sym_LF,
    ACTIONS(347), 1,
      sym_language,
    STATE(114), 1,
      sym_attributes,
  [1802] = 1,
    ACTIONS(349), 4,
      anon_sym_LF,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1809] = 4,
    ACTIONS(325), 1,
      aux_sym_code_token1,
    ACTIONS(351), 1,
      sym_code_block_marker,
    STATE(92), 1,
      aux_sym_code_repeat1,
    STATE(102), 1,
      sym_code,
  [1822] = 1,
    ACTIONS(353), 4,
      anon_sym_LF,
      anon_sym__,
      anon_sym_STAR,
      sym__text,
  [1829] = 4,
    ACTIONS(325), 1,
      aux_sym_code_token1,
    ACTIONS(355), 1,
      sym_code_block_marker,
    STATE(92), 1,
      aux_sym_code_repeat1,
    STATE(110), 1,
      sym_code,
  [1842] = 3,
    ACTIONS(357), 1,
      sym_code_block_marker,
    ACTIONS(359), 1,
      aux_sym_code_token1,
    STATE(88), 1,
      aux_sym_code_repeat1,
  [1852] = 3,
    ACTIONS(337), 1,
      anon_sym_LBRACE,
    ACTIONS(362), 1,
      anon_sym_LF,
    STATE(104), 1,
      sym_attributes,
  [1862] = 3,
    ACTIONS(337), 1,
      anon_sym_LBRACE,
    ACTIONS(364), 1,
      anon_sym_LF,
    STATE(115), 1,
      sym_attributes,
  [1872] = 3,
    ACTIONS(337), 1,
      anon_sym_LBRACE,
    ACTIONS(366), 1,
      anon_sym_LF,
    STATE(97), 1,
      sym_attributes,
  [1882] = 3,
    ACTIONS(325), 1,
      aux_sym_code_token1,
    ACTIONS(368), 1,
      sym_code_block_marker,
    STATE(88), 1,
      aux_sym_code_repeat1,
  [1892] = 3,
    ACTIONS(337), 1,
      anon_sym_LBRACE,
    ACTIONS(370), 1,
      anon_sym_LF,
    STATE(112), 1,
      sym_attributes,
  [1902] = 1,
    ACTIONS(372), 2,
      sym_attribute_value_quoted,
      sym_attribute_value_unquoted,
  [1907] = 1,
    ACTIONS(357), 2,
      sym_code_block_marker,
      aux_sym_code_token1,
  [1912] = 1,
    ACTIONS(374), 1,
      anon_sym_LF,
  [1916] = 1,
    ACTIONS(376), 1,
      anon_sym_LF,
  [1920] = 1,
    ACTIONS(378), 1,
      aux_sym_attribute_id_token1,
  [1924] = 1,
    ACTIONS(380), 1,
      anon_sym_LF,
  [1928] = 1,
    ACTIONS(382), 1,
      anon_sym_EQ,
  [1932] = 1,
    ACTIONS(384), 1,
      sym_code_block_marker,
  [1936] = 1,
    ACTIONS(386), 1,
      sym_code_block_marker,
  [1940] = 1,
    ACTIONS(388), 1,
      sym_code_block_marker,
  [1944] = 1,
    ACTIONS(390), 1,
      anon_sym_LF,
  [1948] = 1,
    ACTIONS(392), 1,
      ts_builtin_sym_end,
  [1952] = 1,
    ACTIONS(394), 1,
      sym_code_block_marker,
  [1956] = 1,
    ACTIONS(396), 1,
      anon_sym_LF,
  [1960] = 1,
    ACTIONS(398), 1,
      sym_code_block_marker,
  [1964] = 1,
    ACTIONS(362), 1,
      anon_sym_LF,
  [1968] = 1,
    ACTIONS(400), 1,
      sym_code_block_marker,
  [1972] = 1,
    ACTIONS(402), 1,
      aux_sym_attribute_id_token1,
  [1976] = 1,
    ACTIONS(404), 1,
      anon_sym_LF,
  [1980] = 1,
    ACTIONS(406), 1,
      anon_sym_LF,
  [1984] = 1,
    ACTIONS(364), 1,
      anon_sym_LF,
  [1988] = 1,
    ACTIONS(408), 1,
      anon_sym_LF,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 47,
  [SMALL_STATE(4)] = 94,
  [SMALL_STATE(5)] = 141,
  [SMALL_STATE(6)] = 188,
  [SMALL_STATE(7)] = 235,
  [SMALL_STATE(8)] = 282,
  [SMALL_STATE(9)] = 329,
  [SMALL_STATE(10)] = 376,
  [SMALL_STATE(11)] = 423,
  [SMALL_STATE(12)] = 470,
  [SMALL_STATE(13)] = 517,
  [SMALL_STATE(14)] = 564,
  [SMALL_STATE(15)] = 611,
  [SMALL_STATE(16)] = 658,
  [SMALL_STATE(17)] = 705,
  [SMALL_STATE(18)] = 731,
  [SMALL_STATE(19)] = 757,
  [SMALL_STATE(20)] = 783,
  [SMALL_STATE(21)] = 809,
  [SMALL_STATE(22)] = 835,
  [SMALL_STATE(23)] = 861,
  [SMALL_STATE(24)] = 887,
  [SMALL_STATE(25)] = 904,
  [SMALL_STATE(26)] = 921,
  [SMALL_STATE(27)] = 938,
  [SMALL_STATE(28)] = 955,
  [SMALL_STATE(29)] = 972,
  [SMALL_STATE(30)] = 989,
  [SMALL_STATE(31)] = 1003,
  [SMALL_STATE(32)] = 1027,
  [SMALL_STATE(33)] = 1047,
  [SMALL_STATE(34)] = 1061,
  [SMALL_STATE(35)] = 1081,
  [SMALL_STATE(36)] = 1101,
  [SMALL_STATE(37)] = 1121,
  [SMALL_STATE(38)] = 1141,
  [SMALL_STATE(39)] = 1161,
  [SMALL_STATE(40)] = 1185,
  [SMALL_STATE(41)] = 1199,
  [SMALL_STATE(42)] = 1213,
  [SMALL_STATE(43)] = 1227,
  [SMALL_STATE(44)] = 1241,
  [SMALL_STATE(45)] = 1255,
  [SMALL_STATE(46)] = 1269,
  [SMALL_STATE(47)] = 1283,
  [SMALL_STATE(48)] = 1297,
  [SMALL_STATE(49)] = 1311,
  [SMALL_STATE(50)] = 1325,
  [SMALL_STATE(51)] = 1339,
  [SMALL_STATE(52)] = 1353,
  [SMALL_STATE(53)] = 1367,
  [SMALL_STATE(54)] = 1381,
  [SMALL_STATE(55)] = 1395,
  [SMALL_STATE(56)] = 1409,
  [SMALL_STATE(57)] = 1423,
  [SMALL_STATE(58)] = 1437,
  [SMALL_STATE(59)] = 1451,
  [SMALL_STATE(60)] = 1465,
  [SMALL_STATE(61)] = 1486,
  [SMALL_STATE(62)] = 1507,
  [SMALL_STATE(63)] = 1524,
  [SMALL_STATE(64)] = 1545,
  [SMALL_STATE(65)] = 1562,
  [SMALL_STATE(66)] = 1583,
  [SMALL_STATE(67)] = 1604,
  [SMALL_STATE(68)] = 1625,
  [SMALL_STATE(69)] = 1646,
  [SMALL_STATE(70)] = 1656,
  [SMALL_STATE(71)] = 1666,
  [SMALL_STATE(72)] = 1676,
  [SMALL_STATE(73)] = 1686,
  [SMALL_STATE(74)] = 1696,
  [SMALL_STATE(75)] = 1709,
  [SMALL_STATE(76)] = 1716,
  [SMALL_STATE(77)] = 1729,
  [SMALL_STATE(78)] = 1736,
  [SMALL_STATE(79)] = 1749,
  [SMALL_STATE(80)] = 1756,
  [SMALL_STATE(81)] = 1769,
  [SMALL_STATE(82)] = 1782,
  [SMALL_STATE(83)] = 1789,
  [SMALL_STATE(84)] = 1802,
  [SMALL_STATE(85)] = 1809,
  [SMALL_STATE(86)] = 1822,
  [SMALL_STATE(87)] = 1829,
  [SMALL_STATE(88)] = 1842,
  [SMALL_STATE(89)] = 1852,
  [SMALL_STATE(90)] = 1862,
  [SMALL_STATE(91)] = 1872,
  [SMALL_STATE(92)] = 1882,
  [SMALL_STATE(93)] = 1892,
  [SMALL_STATE(94)] = 1902,
  [SMALL_STATE(95)] = 1907,
  [SMALL_STATE(96)] = 1912,
  [SMALL_STATE(97)] = 1916,
  [SMALL_STATE(98)] = 1920,
  [SMALL_STATE(99)] = 1924,
  [SMALL_STATE(100)] = 1928,
  [SMALL_STATE(101)] = 1932,
  [SMALL_STATE(102)] = 1936,
  [SMALL_STATE(103)] = 1940,
  [SMALL_STATE(104)] = 1944,
  [SMALL_STATE(105)] = 1948,
  [SMALL_STATE(106)] = 1952,
  [SMALL_STATE(107)] = 1956,
  [SMALL_STATE(108)] = 1960,
  [SMALL_STATE(109)] = 1964,
  [SMALL_STATE(110)] = 1968,
  [SMALL_STATE(111)] = 1972,
  [SMALL_STATE(112)] = 1976,
  [SMALL_STATE(113)] = 1980,
  [SMALL_STATE(114)] = 1984,
  [SMALL_STATE(115)] = 1988,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [69] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [72] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [75] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [78] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [81] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [84] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [87] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(91),
  [90] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [93] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [96] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [99] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(83),
  [102] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(93),
  [105] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [108] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [112] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [116] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_emphasis, 3, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [124] = {.entry = {.count = 3, .reusable = false}}, REDUCE(sym__fallback, 1, -100, 0), REDUCE(sym_emphasis, 3, 0, 0), SHIFT(36),
  [128] = {.entry = {.count = 3, .reusable = false}}, REDUCE(sym__fallback, 1, -100, 0), REDUCE(sym_emphasis, 3, 0, 0), SHIFT(37),
  [132] = {.entry = {.count = 3, .reusable = false}}, REDUCE(sym__fallback, 1, -100, 0), REDUCE(sym_emphasis, 3, 0, 0), SHIFT(64),
  [136] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_heading_repeat1, 2, 0, 0),
  [142] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_heading_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [145] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_heading_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [148] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_heading_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_heading_repeat1, 2, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_strong_emphasis, 3, 0, 0),
  [155] = {.entry = {.count = 3, .reusable = false}}, REDUCE(sym__fallback_star, 1, -100, 0), REDUCE(sym_strong_emphasis, 3, 0, 0), SHIFT(36),
  [159] = {.entry = {.count = 3, .reusable = false}}, REDUCE(sym__fallback_star, 1, -100, 0), REDUCE(sym_strong_emphasis, 3, 0, 0), SHIFT(37),
  [163] = {.entry = {.count = 3, .reusable = false}}, REDUCE(sym__fallback_star, 1, -100, 0), REDUCE(sym_strong_emphasis, 3, 0, 0), SHIFT(62),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_div, 3, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_div, 3, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_div, 5, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_div, 5, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_div, 4, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_div, 4, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block, 4, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_block, 4, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [197] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [199] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [201] = {.entry = {.count = 1, .reusable = false}}, SHIFT(111),
  [203] = {.entry = {.count = 1, .reusable = false}}, SHIFT(100),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__inline, 2, 0, 0),
  [207] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__inline, 2, 0, 0), SHIFT_REPEAT(36),
  [210] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__inline, 2, 0, 0), SHIFT_REPEAT(37),
  [213] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__inline, 2, 0, 0), SHIFT_REPEAT(32),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 2, 0, 0),
  [218] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paragraph, 2, 0, 0),
  [220] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__fallback, 1, -100, 0),
  [222] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym__fallback, 1, -100, 0), SHIFT(36),
  [225] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym__fallback, 1, -100, 0), SHIFT(37),
  [228] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym__fallback, 1, -100, 0), SHIFT(64),
  [231] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__fallback_star, 1, -100, 0),
  [233] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym__fallback_star, 1, -100, 0), SHIFT(36),
  [236] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym__fallback_star, 1, -100, 0), SHIFT(37),
  [239] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym__fallback_star, 1, -100, 0), SHIFT(62),
  [242] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [244] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [248] = {.entry = {.count = 1, .reusable = false}}, SHIFT(96),
  [250] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_block, 6, 0, 0),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block, 6, 0, 0),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_quote, 3, 0, 0),
  [256] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_quote, 3, 0, 0),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading, 3, 0, 0),
  [260] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heading, 3, 0, 0),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block, 3, 0, 0),
  [264] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_block, 3, 0, 0),
  [266] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_div, 6, 0, 0),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_div, 6, 0, 0),
  [270] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_block, 5, 0, 0),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block, 5, 0, 0),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_quote, 2, 0, 0),
  [276] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_quote, 2, 0, 0),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [286] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [290] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [296] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_attributes_repeat1, 2, 0, 0),
  [298] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_attributes_repeat1, 2, 0, 0), SHIFT_REPEAT(98),
  [301] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_attributes_repeat1, 2, 0, 0), SHIFT_REPEAT(111),
  [304] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_attributes_repeat1, 2, 0, 0), SHIFT_REPEAT(100),
  [307] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_class, 2, 0, 0),
  [309] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute_class, 2, 0, 0),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [313] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_attributes_repeat1, 1, 0, 0),
  [315] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_key_value, 3, 0, 0),
  [317] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute_key_value, 3, 0, 0),
  [319] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_id, 2, 0, 0),
  [321] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute_id, 2, 0, 0),
  [323] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [325] = {.entry = {.count = 1, .reusable = false}}, SHIFT(99),
  [327] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attributes, 2, 0, 0),
  [329] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [331] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [333] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attributes, 3, 0, 0),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [341] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [343] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attributes, 4, 0, 0),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [349] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_strong_emphasis, 4, 0, 0),
  [351] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [353] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_emphasis, 4, 0, 0),
  [355] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [357] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_code_repeat1, 2, 0, 0),
  [359] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_code_repeat1, 2, 0, 0), SHIFT_REPEAT(99),
  [362] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [364] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [366] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [368] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code, 1, 0, 0),
  [370] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [372] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [374] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attributes, 2, 0, 0),
  [376] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [378] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [380] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [382] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [384] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [386] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [388] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [390] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [392] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [394] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [396] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attributes, 3, 0, 0),
  [398] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [400] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [402] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [404] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [406] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attributes, 4, 0, 0),
  [408] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__close_paragraph = 0,
  ts_external_token__block_close = 1,
  ts_external_token__div_marker_begin = 2,
  ts_external_token__div_marker_end = 3,
  ts_external_token__block_quote_begin = 4,
  ts_external_token__ignored = 5,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__close_paragraph] = sym__close_paragraph,
  [ts_external_token__block_close] = sym__block_close,
  [ts_external_token__div_marker_begin] = sym__div_marker_begin,
  [ts_external_token__div_marker_end] = sym__div_marker_end,
  [ts_external_token__block_quote_begin] = sym__block_quote_begin,
  [ts_external_token__ignored] = sym__ignored,
};

static const bool ts_external_scanner_states[7][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__close_paragraph] = true,
    [ts_external_token__block_close] = true,
    [ts_external_token__div_marker_begin] = true,
    [ts_external_token__div_marker_end] = true,
    [ts_external_token__block_quote_begin] = true,
    [ts_external_token__ignored] = true,
  },
  [2] = {
    [ts_external_token__div_marker_begin] = true,
    [ts_external_token__block_quote_begin] = true,
  },
  [3] = {
    [ts_external_token__block_close] = true,
    [ts_external_token__div_marker_begin] = true,
    [ts_external_token__block_quote_begin] = true,
  },
  [4] = {
    [ts_external_token__close_paragraph] = true,
  },
  [5] = {
    [ts_external_token__block_close] = true,
    [ts_external_token__div_marker_begin] = true,
    [ts_external_token__div_marker_end] = true,
    [ts_external_token__block_quote_begin] = true,
  },
  [6] = {
    [ts_external_token__div_marker_begin] = true,
    [ts_external_token__div_marker_end] = true,
    [ts_external_token__block_quote_begin] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_sdjot_external_scanner_create(void);
void tree_sitter_sdjot_external_scanner_destroy(void *);
bool tree_sitter_sdjot_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_sdjot_external_scanner_serialize(void *, char *);
void tree_sitter_sdjot_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_sdjot(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_sdjot_external_scanner_create,
      tree_sitter_sdjot_external_scanner_destroy,
      tree_sitter_sdjot_external_scanner_scan,
      tree_sitter_sdjot_external_scanner_serialize,
      tree_sitter_sdjot_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
