#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 98
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 39
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 5
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  anon_sym_LBRACE = 2,
  aux_sym_attributes_token1 = 3,
  anon_sym_RBRACE = 4,
  anon_sym_POUND = 5,
  aux_sym_attribute_id_token1 = 6,
  anon_sym_DOT = 7,
  anon_sym_EQ = 8,
  sym_attribute_key = 9,
  sym_attribute_value_quoted = 10,
  sym_attribute_value_unquoted = 11,
  sym_code_block_marker = 12,
  aux_sym_code_token1 = 13,
  sym_language = 14,
  anon_sym__ = 15,
  sym__text = 16,
  sym__close_paragraph = 17,
  sym__block_close = 18,
  sym__div_marker_begin = 19,
  sym__div_marker_end = 20,
  sym__ignored = 21,
  sym_document = 22,
  sym__block = 23,
  sym_attributes = 24,
  sym_attribute_id = 25,
  sym_attribute_class = 26,
  sym_attribute_key_value = 27,
  sym_div = 28,
  sym_code_block = 29,
  sym_code = 30,
  sym_paragraph = 31,
  aux_sym__inline = 32,
  sym_emphasis = 33,
  sym__fallback = 34,
  aux_sym_document_repeat1 = 35,
  aux_sym_attributes_repeat1 = 36,
  aux_sym_code_repeat1 = 37,
  aux_sym_paragraph_repeat1 = 38,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [anon_sym_LBRACE] = "{",
  [aux_sym_attributes_token1] = "attributes_token1",
  [anon_sym_RBRACE] = "}",
  [anon_sym_POUND] = "#",
  [aux_sym_attribute_id_token1] = "attribute_id_token1",
  [anon_sym_DOT] = ".",
  [anon_sym_EQ] = "=",
  [sym_attribute_key] = "attribute_key",
  [sym_attribute_value_quoted] = "attribute_value_quoted",
  [sym_attribute_value_unquoted] = "attribute_value_unquoted",
  [sym_code_block_marker] = "code_block_marker",
  [aux_sym_code_token1] = "code_token1",
  [sym_language] = "language",
  [anon_sym__] = "_",
  [sym__text] = "_text",
  [sym__close_paragraph] = "_close_paragraph",
  [sym__block_close] = "_block_close",
  [sym__div_marker_begin] = "div_marker",
  [sym__div_marker_end] = "div_marker",
  [sym__ignored] = "_ignored",
  [sym_document] = "document",
  [sym__block] = "_block",
  [sym_attributes] = "attributes",
  [sym_attribute_id] = "attribute_id",
  [sym_attribute_class] = "attribute_class",
  [sym_attribute_key_value] = "attribute_key_value",
  [sym_div] = "div",
  [sym_code_block] = "code_block",
  [sym_code] = "code",
  [sym_paragraph] = "paragraph",
  [aux_sym__inline] = "_inline",
  [sym_emphasis] = "emphasis",
  [sym__fallback] = "_fallback",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_attributes_repeat1] = "attributes_repeat1",
  [aux_sym_code_repeat1] = "code_repeat1",
  [aux_sym_paragraph_repeat1] = "paragraph_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [aux_sym_attributes_token1] = aux_sym_attributes_token1,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_attribute_id_token1] = aux_sym_attribute_id_token1,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_attribute_key] = sym_attribute_key,
  [sym_attribute_value_quoted] = sym_attribute_value_quoted,
  [sym_attribute_value_unquoted] = sym_attribute_value_unquoted,
  [sym_code_block_marker] = sym_code_block_marker,
  [aux_sym_code_token1] = aux_sym_code_token1,
  [sym_language] = sym_language,
  [anon_sym__] = anon_sym__,
  [sym__text] = sym__text,
  [sym__close_paragraph] = sym__close_paragraph,
  [sym__block_close] = sym__block_close,
  [sym__div_marker_begin] = sym__div_marker_begin,
  [sym__div_marker_end] = sym__div_marker_begin,
  [sym__ignored] = sym__ignored,
  [sym_document] = sym_document,
  [sym__block] = sym__block,
  [sym_attributes] = sym_attributes,
  [sym_attribute_id] = sym_attribute_id,
  [sym_attribute_class] = sym_attribute_class,
  [sym_attribute_key_value] = sym_attribute_key_value,
  [sym_div] = sym_div,
  [sym_code_block] = sym_code_block,
  [sym_code] = sym_code,
  [sym_paragraph] = sym_paragraph,
  [aux_sym__inline] = aux_sym__inline,
  [sym_emphasis] = sym_emphasis,
  [sym__fallback] = sym__fallback,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_attributes_repeat1] = aux_sym_attributes_repeat1,
  [aux_sym_code_repeat1] = aux_sym_code_repeat1,
  [aux_sym_paragraph_repeat1] = aux_sym_paragraph_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_attributes_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_attribute_id_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_key] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value_quoted] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value_unquoted] = {
    .visible = true,
    .named = true,
  },
  [sym_code_block_marker] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_code_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_language] = {
    .visible = true,
    .named = true,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [sym__text] = {
    .visible = false,
    .named = true,
  },
  [sym__close_paragraph] = {
    .visible = false,
    .named = true,
  },
  [sym__block_close] = {
    .visible = false,
    .named = true,
  },
  [sym__div_marker_begin] = {
    .visible = true,
    .named = true,
  },
  [sym__div_marker_end] = {
    .visible = true,
    .named = true,
  },
  [sym__ignored] = {
    .visible = false,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__block] = {
    .visible = false,
    .named = true,
  },
  [sym_attributes] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_id] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_class] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_key_value] = {
    .visible = true,
    .named = true,
  },
  [sym_div] = {
    .visible = true,
    .named = true,
  },
  [sym_code_block] = {
    .visible = true,
    .named = true,
  },
  [sym_code] = {
    .visible = true,
    .named = true,
  },
  [sym_paragraph] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__inline] = {
    .visible = false,
    .named = false,
  },
  [sym_emphasis] = {
    .visible = true,
    .named = true,
  },
  [sym__fallback] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_attributes_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_code_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_paragraph_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 4,
  [6] = 6,
  [7] = 7,
  [8] = 6,
  [9] = 9,
  [10] = 10,
  [11] = 10,
  [12] = 9,
  [13] = 13,
  [14] = 13,
  [15] = 15,
  [16] = 16,
  [17] = 16,
  [18] = 18,
  [19] = 19,
  [20] = 15,
  [21] = 19,
  [22] = 22,
  [23] = 23,
  [24] = 23,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 27,
  [29] = 29,
  [30] = 26,
  [31] = 29,
  [32] = 32,
  [33] = 32,
  [34] = 34,
  [35] = 35,
  [36] = 34,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 35,
  [41] = 37,
  [42] = 42,
  [43] = 42,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 38,
  [49] = 45,
  [50] = 46,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 60,
  [62] = 62,
  [63] = 56,
  [64] = 59,
  [65] = 58,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 70,
  [74] = 68,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 72,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 67,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 69,
  [88] = 88,
  [89] = 80,
  [90] = 90,
  [91] = 90,
  [92] = 92,
  [93] = 85,
  [94] = 82,
  [95] = 95,
  [96] = 81,
  [97] = 88,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(13);
      if (lookahead == '\n') ADVANCE(14);
      if (lookahead == '\r') SKIP(0);
      if (lookahead == '"') ADVANCE(8);
      if (lookahead == '#') ADVANCE(19);
      if (lookahead == '\'') ADVANCE(9);
      if (lookahead == '.') ADVANCE(21);
      if (lookahead == '=') ADVANCE(22);
      if (lookahead == '_') ADVANCE(33);
      if (lookahead == '`') ADVANCE(11);
      if (lookahead == '{') ADVANCE(15);
      if (lookahead == '}') ADVANCE(18);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(14);
      if (lookahead == '\r') ADVANCE(36);
      if (lookahead == '_') ADVANCE(33);
      if (lookahead != 0) ADVANCE(34);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(14);
      if (lookahead == '\r') ADVANCE(37);
      if (lookahead == '_') ADVANCE(33);
      if (lookahead == '{') ADVANCE(15);
      if (lookahead != 0) ADVANCE(34);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(14);
      if (lookahead == '\r') SKIP(3);
      if (lookahead == '{') ADVANCE(15);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(32);
      END_STATE();
    case 4:
      if (lookahead == '\r') ADVANCE(16);
      if (lookahead == '#') ADVANCE(19);
      if (lookahead == '.') ADVANCE(21);
      if (lookahead == '}') ADVANCE(18);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead == ':' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 5:
      if (lookahead == '\r') SKIP(5);
      if (lookahead == '#') ADVANCE(19);
      if (lookahead == '.') ADVANCE(21);
      if (lookahead == '}') ADVANCE(18);
      if (lookahead == ':' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 6:
      if (lookahead == '\r') SKIP(6);
      if (lookahead == '"') ADVANCE(8);
      if (lookahead == '\'') ADVANCE(9);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '}') ADVANCE(25);
      END_STATE();
    case 7:
      if (lookahead == '\r') SKIP(7);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '}') ADVANCE(20);
      END_STATE();
    case 8:
      if (lookahead == '"') ADVANCE(24);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == '\'') ADVANCE(24);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '`') ADVANCE(26);
      END_STATE();
    case 11:
      if (lookahead == '`') ADVANCE(10);
      END_STATE();
    case 12:
      if (eof) ADVANCE(13);
      if (lookahead == '\n') ADVANCE(14);
      if (lookahead == '\r') ADVANCE(35);
      if (lookahead == '_') ADVANCE(33);
      if (lookahead == '`') ADVANCE(38);
      if (lookahead != 0) ADVANCE(34);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_attributes_token1);
      if (lookahead == '\r') ADVANCE(16);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(17);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_attributes_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_attribute_id_token1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '}') ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_attribute_key);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_attribute_value_quoted);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_attribute_value_unquoted);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '}') ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_code_block_marker);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_code_block_marker);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_code_token1);
      if (lookahead == '\r') ADVANCE(28);
      if (lookahead == '`') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_code_token1);
      if (lookahead == '`') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_code_token1);
      if (lookahead == '`') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_code_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_language);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{') ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym__);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym__text);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == '\r') ADVANCE(35);
      if (lookahead == '_') ADVANCE(33);
      if (lookahead == '`') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(34);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == '\r') ADVANCE(36);
      if (lookahead == '_') ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(34);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == '\r') ADVANCE(37);
      if (lookahead == '_') ADVANCE(33);
      if (lookahead == '{') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(34);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == '`') ADVANCE(10);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 12, .external_lex_state = 2},
  [2] = {.lex_state = 12, .external_lex_state = 3},
  [3] = {.lex_state = 12, .external_lex_state = 2},
  [4] = {.lex_state = 12, .external_lex_state = 3},
  [5] = {.lex_state = 12, .external_lex_state = 3},
  [6] = {.lex_state = 12, .external_lex_state = 3},
  [7] = {.lex_state = 12, .external_lex_state = 2},
  [8] = {.lex_state = 12, .external_lex_state = 3},
  [9] = {.lex_state = 12, .external_lex_state = 3},
  [10] = {.lex_state = 12, .external_lex_state = 3},
  [11] = {.lex_state = 12, .external_lex_state = 3},
  [12] = {.lex_state = 12, .external_lex_state = 3},
  [13] = {.lex_state = 4},
  [14] = {.lex_state = 4},
  [15] = {.lex_state = 1, .external_lex_state = 4},
  [16] = {.lex_state = 5},
  [17] = {.lex_state = 5},
  [18] = {.lex_state = 1, .external_lex_state = 4},
  [19] = {.lex_state = 5},
  [20] = {.lex_state = 1, .external_lex_state = 4},
  [21] = {.lex_state = 5},
  [22] = {.lex_state = 5},
  [23] = {.lex_state = 5},
  [24] = {.lex_state = 5},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 12, .external_lex_state = 5},
  [27] = {.lex_state = 12, .external_lex_state = 5},
  [28] = {.lex_state = 12, .external_lex_state = 6},
  [29] = {.lex_state = 12, .external_lex_state = 5},
  [30] = {.lex_state = 12, .external_lex_state = 6},
  [31] = {.lex_state = 12, .external_lex_state = 6},
  [32] = {.lex_state = 12, .external_lex_state = 3},
  [33] = {.lex_state = 12, .external_lex_state = 2},
  [34] = {.lex_state = 12, .external_lex_state = 2},
  [35] = {.lex_state = 12, .external_lex_state = 3},
  [36] = {.lex_state = 12, .external_lex_state = 3},
  [37] = {.lex_state = 12, .external_lex_state = 3},
  [38] = {.lex_state = 12, .external_lex_state = 3},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 12, .external_lex_state = 2},
  [41] = {.lex_state = 12, .external_lex_state = 2},
  [42] = {.lex_state = 12, .external_lex_state = 3},
  [43] = {.lex_state = 12, .external_lex_state = 2},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 12, .external_lex_state = 2},
  [46] = {.lex_state = 12, .external_lex_state = 2},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 12, .external_lex_state = 2},
  [49] = {.lex_state = 12, .external_lex_state = 3},
  [50] = {.lex_state = 12, .external_lex_state = 3},
  [51] = {.lex_state = 4},
  [52] = {.lex_state = 4},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 4},
  [55] = {.lex_state = 4},
  [56] = {.lex_state = 28},
  [57] = {.lex_state = 1, .external_lex_state = 4},
  [58] = {.lex_state = 28},
  [59] = {.lex_state = 3},
  [60] = {.lex_state = 28},
  [61] = {.lex_state = 28},
  [62] = {.lex_state = 5},
  [63] = {.lex_state = 28},
  [64] = {.lex_state = 3},
  [65] = {.lex_state = 28},
  [66] = {.lex_state = 28},
  [67] = {.lex_state = 1},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 1},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 28},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 6},
  [77] = {.lex_state = 28},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 7},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 7},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_attribute_value_quoted] = ACTIONS(1),
    [sym_code_block_marker] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [sym__close_paragraph] = ACTIONS(1),
    [sym__block_close] = ACTIONS(1),
    [sym__div_marker_begin] = ACTIONS(1),
    [sym__div_marker_end] = ACTIONS(1),
    [sym__ignored] = ACTIONS(1),
  },
  [1] = {
    [sym_document] = STATE(84),
    [sym__block] = STATE(7),
    [sym_div] = STATE(7),
    [sym_code_block] = STATE(7),
    [sym_paragraph] = STATE(7),
    [aux_sym__inline] = STATE(44),
    [sym_emphasis] = STATE(44),
    [sym__fallback] = STATE(44),
    [aux_sym_document_repeat1] = STATE(7),
    [aux_sym_paragraph_repeat1] = STATE(20),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(5),
    [sym_code_block_marker] = ACTIONS(7),
    [anon_sym__] = ACTIONS(9),
    [sym__text] = ACTIONS(11),
    [sym__div_marker_begin] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(15), 1,
      anon_sym_LF,
    ACTIONS(18), 1,
      sym_code_block_marker,
    ACTIONS(21), 1,
      anon_sym__,
    ACTIONS(24), 1,
      sym__text,
    ACTIONS(27), 1,
      sym__block_close,
    ACTIONS(29), 1,
      sym__div_marker_begin,
    STATE(15), 1,
      aux_sym_paragraph_repeat1,
    STATE(44), 3,
      aux_sym__inline,
      sym_emphasis,
      sym__fallback,
    STATE(2), 5,
      sym__block,
      sym_div,
      sym_code_block,
      sym_paragraph,
      aux_sym_document_repeat1,
  [34] = 9,
    ACTIONS(21), 1,
      anon_sym__,
    ACTIONS(24), 1,
      sym__text,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    ACTIONS(32), 1,
      anon_sym_LF,
    ACTIONS(35), 1,
      sym_code_block_marker,
    ACTIONS(38), 1,
      sym__div_marker_begin,
    STATE(20), 1,
      aux_sym_paragraph_repeat1,
    STATE(44), 3,
      aux_sym__inline,
      sym_emphasis,
      sym__fallback,
    STATE(3), 5,
      sym__block,
      sym_div,
      sym_code_block,
      sym_paragraph,
      aux_sym_document_repeat1,
  [68] = 9,
    ACTIONS(9), 1,
      anon_sym__,
    ACTIONS(11), 1,
      sym__text,
    ACTIONS(41), 1,
      anon_sym_LF,
    ACTIONS(43), 1,
      sym_code_block_marker,
    ACTIONS(45), 1,
      sym__block_close,
    ACTIONS(47), 1,
      sym__div_marker_begin,
    STATE(15), 1,
      aux_sym_paragraph_repeat1,
    STATE(44), 3,
      aux_sym__inline,
      sym_emphasis,
      sym__fallback,
    STATE(8), 5,
      sym__block,
      sym_div,
      sym_code_block,
      sym_paragraph,
      aux_sym_document_repeat1,
  [102] = 9,
    ACTIONS(9), 1,
      anon_sym__,
    ACTIONS(11), 1,
      sym__text,
    ACTIONS(43), 1,
      sym_code_block_marker,
    ACTIONS(47), 1,
      sym__div_marker_begin,
    ACTIONS(49), 1,
      anon_sym_LF,
    ACTIONS(51), 1,
      sym__block_close,
    STATE(15), 1,
      aux_sym_paragraph_repeat1,
    STATE(44), 3,
      aux_sym__inline,
      sym_emphasis,
      sym__fallback,
    STATE(6), 5,
      sym__block,
      sym_div,
      sym_code_block,
      sym_paragraph,
      aux_sym_document_repeat1,
  [136] = 9,
    ACTIONS(9), 1,
      anon_sym__,
    ACTIONS(11), 1,
      sym__text,
    ACTIONS(43), 1,
      sym_code_block_marker,
    ACTIONS(47), 1,
      sym__div_marker_begin,
    ACTIONS(53), 1,
      anon_sym_LF,
    ACTIONS(55), 1,
      sym__block_close,
    STATE(15), 1,
      aux_sym_paragraph_repeat1,
    STATE(44), 3,
      aux_sym__inline,
      sym_emphasis,
      sym__fallback,
    STATE(2), 5,
      sym__block,
      sym_div,
      sym_code_block,
      sym_paragraph,
      aux_sym_document_repeat1,
  [170] = 9,
    ACTIONS(7), 1,
      sym_code_block_marker,
    ACTIONS(9), 1,
      anon_sym__,
    ACTIONS(11), 1,
      sym__text,
    ACTIONS(13), 1,
      sym__div_marker_begin,
    ACTIONS(57), 1,
      ts_builtin_sym_end,
    ACTIONS(59), 1,
      anon_sym_LF,
    STATE(20), 1,
      aux_sym_paragraph_repeat1,
    STATE(44), 3,
      aux_sym__inline,
      sym_emphasis,
      sym__fallback,
    STATE(3), 5,
      sym__block,
      sym_div,
      sym_code_block,
      sym_paragraph,
      aux_sym_document_repeat1,
  [204] = 9,
    ACTIONS(9), 1,
      anon_sym__,
    ACTIONS(11), 1,
      sym__text,
    ACTIONS(43), 1,
      sym_code_block_marker,
    ACTIONS(47), 1,
      sym__div_marker_begin,
    ACTIONS(53), 1,
      anon_sym_LF,
    ACTIONS(61), 1,
      sym__block_close,
    STATE(15), 1,
      aux_sym_paragraph_repeat1,
    STATE(44), 3,
      aux_sym__inline,
      sym_emphasis,
      sym__fallback,
    STATE(2), 5,
      sym__block,
      sym_div,
      sym_code_block,
      sym_paragraph,
      aux_sym_document_repeat1,
  [238] = 9,
    ACTIONS(9), 1,
      anon_sym__,
    ACTIONS(11), 1,
      sym__text,
    ACTIONS(43), 1,
      sym_code_block_marker,
    ACTIONS(47), 1,
      sym__div_marker_begin,
    ACTIONS(63), 1,
      anon_sym_LF,
    ACTIONS(65), 1,
      sym__block_close,
    STATE(15), 1,
      aux_sym_paragraph_repeat1,
    STATE(44), 3,
      aux_sym__inline,
      sym_emphasis,
      sym__fallback,
    STATE(10), 5,
      sym__block,
      sym_div,
      sym_code_block,
      sym_paragraph,
      aux_sym_document_repeat1,
  [272] = 9,
    ACTIONS(9), 1,
      anon_sym__,
    ACTIONS(11), 1,
      sym__text,
    ACTIONS(43), 1,
      sym_code_block_marker,
    ACTIONS(47), 1,
      sym__div_marker_begin,
    ACTIONS(51), 1,
      sym__block_close,
    ACTIONS(53), 1,
      anon_sym_LF,
    STATE(15), 1,
      aux_sym_paragraph_repeat1,
    STATE(44), 3,
      aux_sym__inline,
      sym_emphasis,
      sym__fallback,
    STATE(2), 5,
      sym__block,
      sym_div,
      sym_code_block,
      sym_paragraph,
      aux_sym_document_repeat1,
  [306] = 9,
    ACTIONS(9), 1,
      anon_sym__,
    ACTIONS(11), 1,
      sym__text,
    ACTIONS(43), 1,
      sym_code_block_marker,
    ACTIONS(45), 1,
      sym__block_close,
    ACTIONS(47), 1,
      sym__div_marker_begin,
    ACTIONS(53), 1,
      anon_sym_LF,
    STATE(15), 1,
      aux_sym_paragraph_repeat1,
    STATE(44), 3,
      aux_sym__inline,
      sym_emphasis,
      sym__fallback,
    STATE(2), 5,
      sym__block,
      sym_div,
      sym_code_block,
      sym_paragraph,
      aux_sym_document_repeat1,
  [340] = 9,
    ACTIONS(9), 1,
      anon_sym__,
    ACTIONS(11), 1,
      sym__text,
    ACTIONS(43), 1,
      sym_code_block_marker,
    ACTIONS(47), 1,
      sym__div_marker_begin,
    ACTIONS(67), 1,
      anon_sym_LF,
    ACTIONS(69), 1,
      sym__block_close,
    STATE(15), 1,
      aux_sym_paragraph_repeat1,
    STATE(44), 3,
      aux_sym__inline,
      sym_emphasis,
      sym__fallback,
    STATE(11), 5,
      sym__block,
      sym_div,
      sym_code_block,
      sym_paragraph,
      aux_sym_document_repeat1,
  [374] = 7,
    ACTIONS(71), 1,
      aux_sym_attributes_token1,
    ACTIONS(73), 1,
      anon_sym_RBRACE,
    ACTIONS(75), 1,
      anon_sym_POUND,
    ACTIONS(77), 1,
      anon_sym_DOT,
    ACTIONS(79), 1,
      sym_attribute_key,
    STATE(24), 1,
      aux_sym_attributes_repeat1,
    STATE(52), 3,
      sym_attribute_id,
      sym_attribute_class,
      sym_attribute_key_value,
  [398] = 7,
    ACTIONS(75), 1,
      anon_sym_POUND,
    ACTIONS(77), 1,
      anon_sym_DOT,
    ACTIONS(79), 1,
      sym_attribute_key,
    ACTIONS(81), 1,
      aux_sym_attributes_token1,
    ACTIONS(83), 1,
      anon_sym_RBRACE,
    STATE(23), 1,
      aux_sym_attributes_repeat1,
    STATE(52), 3,
      sym_attribute_id,
      sym_attribute_class,
      sym_attribute_key_value,
  [422] = 6,
    ACTIONS(9), 1,
      anon_sym__,
    ACTIONS(11), 1,
      sym__text,
    ACTIONS(85), 1,
      anon_sym_LF,
    ACTIONS(87), 1,
      sym__close_paragraph,
    STATE(18), 1,
      aux_sym_paragraph_repeat1,
    STATE(44), 3,
      aux_sym__inline,
      sym_emphasis,
      sym__fallback,
  [443] = 6,
    ACTIONS(89), 1,
      anon_sym_RBRACE,
    ACTIONS(91), 1,
      anon_sym_POUND,
    ACTIONS(93), 1,
      anon_sym_DOT,
    ACTIONS(95), 1,
      sym_attribute_key,
    STATE(22), 1,
      aux_sym_attributes_repeat1,
    STATE(52), 3,
      sym_attribute_id,
      sym_attribute_class,
      sym_attribute_key_value,
  [464] = 6,
    ACTIONS(91), 1,
      anon_sym_POUND,
    ACTIONS(93), 1,
      anon_sym_DOT,
    ACTIONS(95), 1,
      sym_attribute_key,
    ACTIONS(97), 1,
      anon_sym_RBRACE,
    STATE(22), 1,
      aux_sym_attributes_repeat1,
    STATE(52), 3,
      sym_attribute_id,
      sym_attribute_class,
      sym_attribute_key_value,
  [485] = 6,
    ACTIONS(99), 1,
      anon_sym_LF,
    ACTIONS(101), 1,
      anon_sym__,
    ACTIONS(104), 1,
      sym__text,
    ACTIONS(107), 1,
      sym__close_paragraph,
    STATE(18), 1,
      aux_sym_paragraph_repeat1,
    STATE(44), 3,
      aux_sym__inline,
      sym_emphasis,
      sym__fallback,
  [506] = 6,
    ACTIONS(91), 1,
      anon_sym_POUND,
    ACTIONS(93), 1,
      anon_sym_DOT,
    ACTIONS(95), 1,
      sym_attribute_key,
    ACTIONS(109), 1,
      anon_sym_RBRACE,
    STATE(17), 1,
      aux_sym_attributes_repeat1,
    STATE(52), 3,
      sym_attribute_id,
      sym_attribute_class,
      sym_attribute_key_value,
  [527] = 6,
    ACTIONS(9), 1,
      anon_sym__,
    ACTIONS(11), 1,
      sym__text,
    ACTIONS(111), 1,
      anon_sym_LF,
    ACTIONS(113), 1,
      sym__close_paragraph,
    STATE(18), 1,
      aux_sym_paragraph_repeat1,
    STATE(44), 3,
      aux_sym__inline,
      sym_emphasis,
      sym__fallback,
  [548] = 6,
    ACTIONS(91), 1,
      anon_sym_POUND,
    ACTIONS(93), 1,
      anon_sym_DOT,
    ACTIONS(95), 1,
      sym_attribute_key,
    ACTIONS(115), 1,
      anon_sym_RBRACE,
    STATE(16), 1,
      aux_sym_attributes_repeat1,
    STATE(52), 3,
      sym_attribute_id,
      sym_attribute_class,
      sym_attribute_key_value,
  [569] = 6,
    ACTIONS(117), 1,
      anon_sym_RBRACE,
    ACTIONS(119), 1,
      anon_sym_POUND,
    ACTIONS(122), 1,
      anon_sym_DOT,
    ACTIONS(125), 1,
      sym_attribute_key,
    STATE(22), 1,
      aux_sym_attributes_repeat1,
    STATE(52), 3,
      sym_attribute_id,
      sym_attribute_class,
      sym_attribute_key_value,
  [590] = 6,
    ACTIONS(91), 1,
      anon_sym_POUND,
    ACTIONS(93), 1,
      anon_sym_DOT,
    ACTIONS(95), 1,
      sym_attribute_key,
    ACTIONS(109), 1,
      anon_sym_RBRACE,
    STATE(22), 1,
      aux_sym_attributes_repeat1,
    STATE(52), 3,
      sym_attribute_id,
      sym_attribute_class,
      sym_attribute_key_value,
  [611] = 6,
    ACTIONS(91), 1,
      anon_sym_POUND,
    ACTIONS(93), 1,
      anon_sym_DOT,
    ACTIONS(95), 1,
      sym_attribute_key,
    ACTIONS(115), 1,
      anon_sym_RBRACE,
    STATE(22), 1,
      aux_sym_attributes_repeat1,
    STATE(52), 3,
      sym_attribute_id,
      sym_attribute_class,
      sym_attribute_key_value,
  [632] = 6,
    ACTIONS(128), 1,
      anon_sym_LF,
    ACTIONS(130), 1,
      anon_sym_LBRACE,
    ACTIONS(132), 1,
      anon_sym__,
    ACTIONS(136), 1,
      sym__text,
    STATE(75), 1,
      sym_attributes,
    STATE(53), 3,
      aux_sym__inline,
      sym_emphasis,
      sym__fallback,
  [653] = 3,
    ACTIONS(144), 1,
      sym__div_marker_end,
    ACTIONS(142), 2,
      sym__block_close,
      sym__div_marker_begin,
    ACTIONS(140), 4,
      anon_sym_LF,
      sym_code_block_marker,
      anon_sym__,
      sym__text,
  [667] = 3,
    ACTIONS(150), 1,
      sym__div_marker_end,
    ACTIONS(148), 2,
      sym__block_close,
      sym__div_marker_begin,
    ACTIONS(146), 4,
      anon_sym_LF,
      sym_code_block_marker,
      anon_sym__,
      sym__text,
  [681] = 3,
    ACTIONS(152), 1,
      sym__div_marker_end,
    ACTIONS(148), 2,
      sym__div_marker_begin,
      ts_builtin_sym_end,
    ACTIONS(146), 4,
      anon_sym_LF,
      sym_code_block_marker,
      anon_sym__,
      sym__text,
  [695] = 3,
    ACTIONS(158), 1,
      sym__div_marker_end,
    ACTIONS(156), 2,
      sym__block_close,
      sym__div_marker_begin,
    ACTIONS(154), 4,
      anon_sym_LF,
      sym_code_block_marker,
      anon_sym__,
      sym__text,
  [709] = 3,
    ACTIONS(160), 1,
      sym__div_marker_end,
    ACTIONS(142), 2,
      sym__div_marker_begin,
      ts_builtin_sym_end,
    ACTIONS(140), 4,
      anon_sym_LF,
      sym_code_block_marker,
      anon_sym__,
      sym__text,
  [723] = 3,
    ACTIONS(162), 1,
      sym__div_marker_end,
    ACTIONS(156), 2,
      sym__div_marker_begin,
      ts_builtin_sym_end,
    ACTIONS(154), 4,
      anon_sym_LF,
      sym_code_block_marker,
      anon_sym__,
      sym__text,
  [737] = 2,
    ACTIONS(142), 2,
      sym__block_close,
      sym__div_marker_begin,
    ACTIONS(140), 4,
      anon_sym_LF,
      sym_code_block_marker,
      anon_sym__,
      sym__text,
  [748] = 2,
    ACTIONS(142), 2,
      sym__div_marker_begin,
      ts_builtin_sym_end,
    ACTIONS(140), 4,
      anon_sym_LF,
      sym_code_block_marker,
      anon_sym__,
      sym__text,
  [759] = 2,
    ACTIONS(164), 2,
      sym__div_marker_begin,
      ts_builtin_sym_end,
    ACTIONS(166), 4,
      anon_sym_LF,
      sym_code_block_marker,
      anon_sym__,
      sym__text,
  [770] = 2,
    ACTIONS(156), 2,
      sym__block_close,
      sym__div_marker_begin,
    ACTIONS(154), 4,
      anon_sym_LF,
      sym_code_block_marker,
      anon_sym__,
      sym__text,
  [781] = 2,
    ACTIONS(164), 2,
      sym__block_close,
      sym__div_marker_begin,
    ACTIONS(166), 4,
      anon_sym_LF,
      sym_code_block_marker,
      anon_sym__,
      sym__text,
  [792] = 2,
    ACTIONS(170), 2,
      sym__block_close,
      sym__div_marker_begin,
    ACTIONS(168), 4,
      anon_sym_LF,
      sym_code_block_marker,
      anon_sym__,
      sym__text,
  [803] = 2,
    ACTIONS(174), 2,
      sym__block_close,
      sym__div_marker_begin,
    ACTIONS(172), 4,
      anon_sym_LF,
      sym_code_block_marker,
      anon_sym__,
      sym__text,
  [814] = 4,
    ACTIONS(176), 1,
      anon_sym_LF,
    ACTIONS(178), 1,
      anon_sym__,
    ACTIONS(181), 1,
      sym__text,
    STATE(53), 3,
      aux_sym__inline,
      sym_emphasis,
      sym__fallback,
  [829] = 2,
    ACTIONS(156), 2,
      sym__div_marker_begin,
      ts_builtin_sym_end,
    ACTIONS(154), 4,
      anon_sym_LF,
      sym_code_block_marker,
      anon_sym__,
      sym__text,
  [840] = 2,
    ACTIONS(170), 2,
      sym__div_marker_begin,
      ts_builtin_sym_end,
    ACTIONS(168), 4,
      anon_sym_LF,
      sym_code_block_marker,
      anon_sym__,
      sym__text,
  [851] = 2,
    ACTIONS(186), 2,
      sym__block_close,
      sym__div_marker_begin,
    ACTIONS(184), 4,
      anon_sym_LF,
      sym_code_block_marker,
      anon_sym__,
      sym__text,
  [862] = 2,
    ACTIONS(186), 2,
      sym__div_marker_begin,
      ts_builtin_sym_end,
    ACTIONS(184), 4,
      anon_sym_LF,
      sym_code_block_marker,
      anon_sym__,
      sym__text,
  [873] = 4,
    ACTIONS(9), 1,
      anon_sym__,
    ACTIONS(188), 1,
      anon_sym_LF,
    ACTIONS(190), 1,
      sym__text,
    STATE(47), 3,
      aux_sym__inline,
      sym_emphasis,
      sym__fallback,
  [888] = 2,
    ACTIONS(192), 2,
      sym__div_marker_begin,
      ts_builtin_sym_end,
    ACTIONS(194), 4,
      anon_sym_LF,
      sym_code_block_marker,
      anon_sym__,
      sym__text,
  [899] = 2,
    ACTIONS(196), 2,
      sym__div_marker_begin,
      ts_builtin_sym_end,
    ACTIONS(198), 4,
      anon_sym_LF,
      sym_code_block_marker,
      anon_sym__,
      sym__text,
  [910] = 4,
    ACTIONS(200), 1,
      anon_sym_LF,
    ACTIONS(202), 1,
      anon_sym__,
    ACTIONS(205), 1,
      sym__text,
    STATE(47), 3,
      aux_sym__inline,
      sym_emphasis,
      sym__fallback,
  [925] = 2,
    ACTIONS(174), 2,
      sym__div_marker_begin,
      ts_builtin_sym_end,
    ACTIONS(172), 4,
      anon_sym_LF,
      sym_code_block_marker,
      anon_sym__,
      sym__text,
  [936] = 2,
    ACTIONS(192), 2,
      sym__block_close,
      sym__div_marker_begin,
    ACTIONS(194), 4,
      anon_sym_LF,
      sym_code_block_marker,
      anon_sym__,
      sym__text,
  [947] = 2,
    ACTIONS(196), 2,
      sym__block_close,
      sym__div_marker_begin,
    ACTIONS(198), 4,
      anon_sym_LF,
      sym_code_block_marker,
      anon_sym__,
      sym__text,
  [958] = 2,
    ACTIONS(208), 1,
      aux_sym_attributes_token1,
    ACTIONS(210), 4,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_DOT,
      sym_attribute_key,
  [968] = 2,
    ACTIONS(212), 1,
      aux_sym_attributes_token1,
    ACTIONS(214), 4,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_DOT,
      sym_attribute_key,
  [978] = 3,
    ACTIONS(190), 1,
      sym__text,
    ACTIONS(216), 1,
      anon_sym__,
    STATE(47), 3,
      aux_sym__inline,
      sym_emphasis,
      sym__fallback,
  [990] = 2,
    ACTIONS(218), 1,
      aux_sym_attributes_token1,
    ACTIONS(220), 4,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_DOT,
      sym_attribute_key,
  [1000] = 2,
    ACTIONS(222), 1,
      aux_sym_attributes_token1,
    ACTIONS(224), 4,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_DOT,
      sym_attribute_key,
  [1010] = 4,
    ACTIONS(226), 1,
      sym_code_block_marker,
    ACTIONS(228), 1,
      aux_sym_code_token1,
    STATE(71), 1,
      aux_sym_code_repeat1,
    STATE(89), 1,
      sym_code,
  [1023] = 2,
    ACTIONS(107), 1,
      sym__close_paragraph,
    ACTIONS(99), 3,
      anon_sym_LF,
      anon_sym__,
      sym__text,
  [1032] = 4,
    ACTIONS(228), 1,
      aux_sym_code_token1,
    ACTIONS(230), 1,
      sym_code_block_marker,
    STATE(71), 1,
      aux_sym_code_repeat1,
    STATE(90), 1,
      sym_code,
  [1045] = 4,
    ACTIONS(232), 1,
      anon_sym_LF,
    ACTIONS(234), 1,
      anon_sym_LBRACE,
    ACTIONS(236), 1,
      sym_language,
    STATE(96), 1,
      sym_attributes,
  [1058] = 4,
    ACTIONS(228), 1,
      aux_sym_code_token1,
    ACTIONS(238), 1,
      sym_code_block_marker,
    STATE(71), 1,
      aux_sym_code_repeat1,
    STATE(85), 1,
      sym_code,
  [1071] = 4,
    ACTIONS(228), 1,
      aux_sym_code_token1,
    ACTIONS(240), 1,
      sym_code_block_marker,
    STATE(71), 1,
      aux_sym_code_repeat1,
    STATE(93), 1,
      sym_code,
  [1084] = 1,
    ACTIONS(117), 4,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_DOT,
      sym_attribute_key,
  [1091] = 4,
    ACTIONS(228), 1,
      aux_sym_code_token1,
    ACTIONS(242), 1,
      sym_code_block_marker,
    STATE(71), 1,
      aux_sym_code_repeat1,
    STATE(80), 1,
      sym_code,
  [1104] = 4,
    ACTIONS(234), 1,
      anon_sym_LBRACE,
    ACTIONS(244), 1,
      anon_sym_LF,
    ACTIONS(246), 1,
      sym_language,
    STATE(81), 1,
      sym_attributes,
  [1117] = 4,
    ACTIONS(228), 1,
      aux_sym_code_token1,
    ACTIONS(248), 1,
      sym_code_block_marker,
    STATE(71), 1,
      aux_sym_code_repeat1,
    STATE(91), 1,
      sym_code,
  [1130] = 3,
    ACTIONS(250), 1,
      sym_code_block_marker,
    ACTIONS(252), 1,
      aux_sym_code_token1,
    STATE(66), 1,
      aux_sym_code_repeat1,
  [1140] = 1,
    ACTIONS(255), 3,
      anon_sym_LF,
      anon_sym__,
      sym__text,
  [1146] = 3,
    ACTIONS(234), 1,
      anon_sym_LBRACE,
    ACTIONS(257), 1,
      anon_sym_LF,
    STATE(97), 1,
      sym_attributes,
  [1156] = 1,
    ACTIONS(259), 3,
      anon_sym_LF,
      anon_sym__,
      sym__text,
  [1162] = 3,
    ACTIONS(234), 1,
      anon_sym_LBRACE,
    ACTIONS(261), 1,
      anon_sym_LF,
    STATE(94), 1,
      sym_attributes,
  [1172] = 3,
    ACTIONS(228), 1,
      aux_sym_code_token1,
    ACTIONS(263), 1,
      sym_code_block_marker,
    STATE(66), 1,
      aux_sym_code_repeat1,
  [1182] = 1,
    ACTIONS(265), 3,
      anon_sym_LF,
      anon_sym__,
      sym__text,
  [1188] = 3,
    ACTIONS(234), 1,
      anon_sym_LBRACE,
    ACTIONS(267), 1,
      anon_sym_LF,
    STATE(82), 1,
      sym_attributes,
  [1198] = 3,
    ACTIONS(234), 1,
      anon_sym_LBRACE,
    ACTIONS(269), 1,
      anon_sym_LF,
    STATE(88), 1,
      sym_attributes,
  [1208] = 1,
    ACTIONS(271), 3,
      anon_sym_LF,
      anon_sym__,
      sym__text,
  [1214] = 1,
    ACTIONS(273), 2,
      sym_attribute_value_quoted,
      sym_attribute_value_unquoted,
  [1219] = 1,
    ACTIONS(250), 2,
      sym_code_block_marker,
      aux_sym_code_token1,
  [1224] = 1,
    ACTIONS(275), 1,
      anon_sym_EQ,
  [1228] = 1,
    ACTIONS(277), 1,
      anon_sym_LF,
  [1232] = 1,
    ACTIONS(279), 1,
      sym_code_block_marker,
  [1236] = 1,
    ACTIONS(269), 1,
      anon_sym_LF,
  [1240] = 1,
    ACTIONS(281), 1,
      anon_sym_LF,
  [1244] = 1,
    ACTIONS(283), 1,
      anon_sym_LF,
  [1248] = 1,
    ACTIONS(285), 1,
      ts_builtin_sym_end,
  [1252] = 1,
    ACTIONS(287), 1,
      sym_code_block_marker,
  [1256] = 1,
    ACTIONS(289), 1,
      aux_sym_attribute_id_token1,
  [1260] = 1,
    ACTIONS(291), 1,
      anon_sym_LF,
  [1264] = 1,
    ACTIONS(293), 1,
      anon_sym_LF,
  [1268] = 1,
    ACTIONS(295), 1,
      sym_code_block_marker,
  [1272] = 1,
    ACTIONS(297), 1,
      sym_code_block_marker,
  [1276] = 1,
    ACTIONS(299), 1,
      sym_code_block_marker,
  [1280] = 1,
    ACTIONS(301), 1,
      aux_sym_attribute_id_token1,
  [1284] = 1,
    ACTIONS(303), 1,
      sym_code_block_marker,
  [1288] = 1,
    ACTIONS(305), 1,
      anon_sym_LF,
  [1292] = 1,
    ACTIONS(307), 1,
      anon_sym_LF,
  [1296] = 1,
    ACTIONS(257), 1,
      anon_sym_LF,
  [1300] = 1,
    ACTIONS(309), 1,
      anon_sym_LF,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 34,
  [SMALL_STATE(4)] = 68,
  [SMALL_STATE(5)] = 102,
  [SMALL_STATE(6)] = 136,
  [SMALL_STATE(7)] = 170,
  [SMALL_STATE(8)] = 204,
  [SMALL_STATE(9)] = 238,
  [SMALL_STATE(10)] = 272,
  [SMALL_STATE(11)] = 306,
  [SMALL_STATE(12)] = 340,
  [SMALL_STATE(13)] = 374,
  [SMALL_STATE(14)] = 398,
  [SMALL_STATE(15)] = 422,
  [SMALL_STATE(16)] = 443,
  [SMALL_STATE(17)] = 464,
  [SMALL_STATE(18)] = 485,
  [SMALL_STATE(19)] = 506,
  [SMALL_STATE(20)] = 527,
  [SMALL_STATE(21)] = 548,
  [SMALL_STATE(22)] = 569,
  [SMALL_STATE(23)] = 590,
  [SMALL_STATE(24)] = 611,
  [SMALL_STATE(25)] = 632,
  [SMALL_STATE(26)] = 653,
  [SMALL_STATE(27)] = 667,
  [SMALL_STATE(28)] = 681,
  [SMALL_STATE(29)] = 695,
  [SMALL_STATE(30)] = 709,
  [SMALL_STATE(31)] = 723,
  [SMALL_STATE(32)] = 737,
  [SMALL_STATE(33)] = 748,
  [SMALL_STATE(34)] = 759,
  [SMALL_STATE(35)] = 770,
  [SMALL_STATE(36)] = 781,
  [SMALL_STATE(37)] = 792,
  [SMALL_STATE(38)] = 803,
  [SMALL_STATE(39)] = 814,
  [SMALL_STATE(40)] = 829,
  [SMALL_STATE(41)] = 840,
  [SMALL_STATE(42)] = 851,
  [SMALL_STATE(43)] = 862,
  [SMALL_STATE(44)] = 873,
  [SMALL_STATE(45)] = 888,
  [SMALL_STATE(46)] = 899,
  [SMALL_STATE(47)] = 910,
  [SMALL_STATE(48)] = 925,
  [SMALL_STATE(49)] = 936,
  [SMALL_STATE(50)] = 947,
  [SMALL_STATE(51)] = 958,
  [SMALL_STATE(52)] = 968,
  [SMALL_STATE(53)] = 978,
  [SMALL_STATE(54)] = 990,
  [SMALL_STATE(55)] = 1000,
  [SMALL_STATE(56)] = 1010,
  [SMALL_STATE(57)] = 1023,
  [SMALL_STATE(58)] = 1032,
  [SMALL_STATE(59)] = 1045,
  [SMALL_STATE(60)] = 1058,
  [SMALL_STATE(61)] = 1071,
  [SMALL_STATE(62)] = 1084,
  [SMALL_STATE(63)] = 1091,
  [SMALL_STATE(64)] = 1104,
  [SMALL_STATE(65)] = 1117,
  [SMALL_STATE(66)] = 1130,
  [SMALL_STATE(67)] = 1140,
  [SMALL_STATE(68)] = 1146,
  [SMALL_STATE(69)] = 1156,
  [SMALL_STATE(70)] = 1162,
  [SMALL_STATE(71)] = 1172,
  [SMALL_STATE(72)] = 1182,
  [SMALL_STATE(73)] = 1188,
  [SMALL_STATE(74)] = 1198,
  [SMALL_STATE(75)] = 1208,
  [SMALL_STATE(76)] = 1214,
  [SMALL_STATE(77)] = 1219,
  [SMALL_STATE(78)] = 1224,
  [SMALL_STATE(79)] = 1228,
  [SMALL_STATE(80)] = 1232,
  [SMALL_STATE(81)] = 1236,
  [SMALL_STATE(82)] = 1240,
  [SMALL_STATE(83)] = 1244,
  [SMALL_STATE(84)] = 1248,
  [SMALL_STATE(85)] = 1252,
  [SMALL_STATE(86)] = 1256,
  [SMALL_STATE(87)] = 1260,
  [SMALL_STATE(88)] = 1264,
  [SMALL_STATE(89)] = 1268,
  [SMALL_STATE(90)] = 1272,
  [SMALL_STATE(91)] = 1276,
  [SMALL_STATE(92)] = 1280,
  [SMALL_STATE(93)] = 1284,
  [SMALL_STATE(94)] = 1288,
  [SMALL_STATE(95)] = 1292,
  [SMALL_STATE(96)] = 1296,
  [SMALL_STATE(97)] = 1300,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [15] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [18] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [21] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [24] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(64),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_paragraph_repeat1, 2, 0, 0),
  [101] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_paragraph_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [104] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_paragraph_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_attributes_repeat1, 2, 0, 0),
  [119] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_attributes_repeat1, 2, 0, 0), SHIFT_REPEAT(92),
  [122] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_attributes_repeat1, 2, 0, 0), SHIFT_REPEAT(86),
  [125] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_attributes_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_emphasis, 3, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [132] = {.entry = {.count = 3, .reusable = false}}, REDUCE(sym__fallback, 1, -100, 0), REDUCE(sym_emphasis, 3, 0, 0), SHIFT(39),
  [136] = {.entry = {.count = 3, .reusable = false}}, REDUCE(sym__fallback, 1, -100, 0), REDUCE(sym_emphasis, 3, 0, 0), SHIFT(53),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_div, 5, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_div, 5, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_div, 3, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_div, 3, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_div, 4, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_div, 4, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block, 3, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_block, 3, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paragraph, 2, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 2, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_block, 4, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block, 4, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__fallback, 1, -100, 0),
  [178] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym__fallback, 1, -100, 0), SHIFT(39),
  [181] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym__fallback, 1, -100, 0), SHIFT(53),
  [184] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_block, 5, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block, 5, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [190] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block, 6, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_block, 6, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_div, 6, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_div, 6, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__inline, 2, 0, 0),
  [202] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__inline, 2, 0, 0), SHIFT_REPEAT(39),
  [205] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__inline, 2, 0, 0), SHIFT_REPEAT(47),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_class, 2, 0, 0),
  [210] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute_class, 2, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [214] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_attributes_repeat1, 1, 0, 0),
  [216] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_id, 2, 0, 0),
  [220] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute_id, 2, 0, 0),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_key_value, 3, 0, 0),
  [224] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute_key_value, 3, 0, 0),
  [226] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [228] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [230] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [238] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [240] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [242] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [248] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [250] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_code_repeat1, 2, 0, 0),
  [252] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_code_repeat1, 2, 0, 0), SHIFT_REPEAT(95),
  [255] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attributes, 2, 0, 0),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [259] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attributes, 3, 0, 0),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [263] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code, 1, 0, 0),
  [265] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attributes, 4, 0, 0),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [271] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_emphasis, 4, 0, 0),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [277] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attributes, 4, 0, 0),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [283] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attributes, 2, 0, 0),
  [285] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [291] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attributes, 3, 0, 0),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__close_paragraph = 0,
  ts_external_token__block_close = 1,
  ts_external_token__div_marker_begin = 2,
  ts_external_token__div_marker_end = 3,
  ts_external_token__ignored = 4,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__close_paragraph] = sym__close_paragraph,
  [ts_external_token__block_close] = sym__block_close,
  [ts_external_token__div_marker_begin] = sym__div_marker_begin,
  [ts_external_token__div_marker_end] = sym__div_marker_end,
  [ts_external_token__ignored] = sym__ignored,
};

static const bool ts_external_scanner_states[7][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__close_paragraph] = true,
    [ts_external_token__block_close] = true,
    [ts_external_token__div_marker_begin] = true,
    [ts_external_token__div_marker_end] = true,
    [ts_external_token__ignored] = true,
  },
  [2] = {
    [ts_external_token__div_marker_begin] = true,
  },
  [3] = {
    [ts_external_token__block_close] = true,
    [ts_external_token__div_marker_begin] = true,
  },
  [4] = {
    [ts_external_token__close_paragraph] = true,
  },
  [5] = {
    [ts_external_token__block_close] = true,
    [ts_external_token__div_marker_begin] = true,
    [ts_external_token__div_marker_end] = true,
  },
  [6] = {
    [ts_external_token__div_marker_begin] = true,
    [ts_external_token__div_marker_end] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_sdjot_external_scanner_create(void);
void tree_sitter_sdjot_external_scanner_destroy(void *);
bool tree_sitter_sdjot_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_sdjot_external_scanner_serialize(void *, char *);
void tree_sitter_sdjot_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_sdjot(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_sdjot_external_scanner_create,
      tree_sitter_sdjot_external_scanner_destroy,
      tree_sitter_sdjot_external_scanner_scan,
      tree_sitter_sdjot_external_scanner_serialize,
      tree_sitter_sdjot_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
